[package]
name = "osg-server"
version.workspace = true
edition.workspace = true

[features]
profile = ["bevy/trace_chrome"]

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["std", "multi_threaded", "bevy_state", "bevy_asset", "bevy_log", "serialize"] }
parry3d-f64.workspace = true
rayon = "1.12"
ahash = "0.8"
ordered-float = "5.5"
hifitime = "4.3.1"
smol_str = { version = "0.3.6", features = ["serde"] }
rand_chacha = "0.10"
blake3 = "1.8"
rusqlite = { version = "0.40.2", features = ["bundled", "fallible_uint"] }
osg-space = { path = "../osg-space" }
osg-spatial-bvh = { path = "../osg-spatial-bvh" }
osg-ship-api = { path = "../osg-ship-api" }
osg-ship-wasm = { path = "../osg-ship-wasm" }
postcard = { version = "1.1", features = ["use-std"] }
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
osg-model = { path = "../osg-model" }
osg-net = { path = "../osg-net" }
osg-protocol = { path = "../osg-protocol" }
osg-ships = { path = "../osg-ships" }
osg-universe = { path = "../osg-universe" }
tokio = { version = "1.53", features = ["full"] }
ed25519-dalek = "2.2"

[dev-dependencies]
osg-example-controller = { path = "../osg-example-controller" }
wat = "1.0"
osg-client = { path = "../osg-client" }

[dependencies.rand]
version = "0.10"

[dev-dependencies.zstd]
version = "0.13.3"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_dylib.workspace = true
