name = "Elysium system"
position_um = ["132450220000000000000000", "0", "0"]
[[bodies]]
name = "Elysium"
class = "star"
lumens = 3.6e28
mass = "1 massSol"
radius = "696000 km"
rotation_period = "25 d"
