name = "Meridian system"
position_um = ["113528760000000000000000", "0", "0"]
[[bodies]]
name = "Meridian"
class = "star"
lumens = 3.6e28
mass = "1 massSol"
radius = "696000 km"
rotation_period = "25 d"
