[package]
name = "osg-net"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
osg-model = { path = "../osg-model" }
osg-protocol = { path = "../osg-protocol" }
tokio = { version = "1.53", features = ["rt-multi-thread", "net", "io-util", "sync", "time", "macros"] }
ed25519-dalek = "2.2"
x25519-dalek = "2.0"
chacha20poly1305 = "0.10"
blake3 = "1.8"
rand = "0.8"
zstd = "=0.13.3"
picomux = "0.3.1"
