/* Generated by tools/generate_ship_bindings.py. wasm32, little endian. */
#ifndef OSG_SHIP_H
#define OSG_SHIP_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
#define SHIP_ASSERT static_assert
#define SHIP_ALIGNOF alignof
extern "C" {
#else
#define SHIP_ASSERT _Static_assert
#define SHIP_ALIGNOF _Alignof
#endif
#if defined(__wasm__)
#define SHIP_IMPORT(name) __attribute__((import_module("ship_v32"), import_name(name)))
#else
#define SHIP_IMPORT(name)
#endif
#define SHIP_API_VERSION (34)
#define SHIP_ERR_BUFFER (-2)
#define SHIP_ERR_ARGUMENT (-3)
#define SHIP_ERR_UNAVAILABLE (-4)
#define SHIP_ERR_LIMIT (-5)
#define SHIP_ERR_HANDLE (-6)
#define SHIP_ERR_UNSUPPORTED (-7)
#define SHIP_CALL_GAS (100)
#define SHIP_SCAN_GAS_PER_OBJECT (3000)
#define SHIP_MAX_CONTACTS (256)
#define SHIP_MAX_TRACKS (512)
#define SHIP_MAX_SNAPSHOTS (8)
#define SHIP_MAX_MARKERS (64)
#define SHIP_MAX_PATHS (8)
#define SHIP_MAX_PATH_VERTICES (128)
#define SHIP_MAX_TOTAL_VERTICES (1024)
#define SHIP_MAX_SCREENS (8)
#define SHIP_MAX_SCREEN_PRIMITIVES (256)
#define SHIP_MAX_SCREEN_PAYLOAD (65536)
#define SHIP_MAX_INPUTS (256)
#define SHIP_INTEREST_MARKERS (1)
#define SHIP_INTEREST_PATHS (2)
#define SHIP_FIRST_CALLBACK (1)
#define SHIP_OPERATIONAL (1)
#define SHIP_POWERED (2)
#define SHIP_CONTROL_ENABLED (1)
#define SHIP_CONTACT_SHIP (0)
#define SHIP_CONTACT_CELESTIAL (1)
#define SHIP_CONTACT_OTHER (2)
#define SHIP_DEVICE_ACCELEROMETER (0)
#define SHIP_DEVICE_COMPUTER (1)
#define SHIP_DEVICE_STORAGE (2)
#define SHIP_DEVICE_BATTERY (3)
#define SHIP_DEVICE_ENGINE (4)
#define SHIP_DEVICE_TORQUER (5)
#define SHIP_DEVICE_GENERATOR (6)
#define SHIP_DEVICE_SHIELD (7)
#define SHIP_DEVICE_SENSOR (8)
#define SHIP_SET_THROTTLE (0)
#define SHIP_SET_TORQUE (1)
#define SHIP_SET_GENERATOR_DEMAND (2)
#define SHIP_SET_SHIELD_ENABLED (3)
#define SHIP_SET_SENSOR_ENABLED (4)
#define SHIP_REQUEST_THROTTLE (11)
#define SHIP_REQUEST_MANUAL (0)
#define SHIP_REQUEST_HOLD_ATTITUDE (1)
#define SHIP_REQUEST_STOP_GUIDANCE (2)
#define SHIP_REQUEST_AIM_DIRECTION (3)
#define SHIP_REQUEST_AIM_CONTACT (4)
#define SHIP_REQUEST_SELECT_TARGET (5)
#define SHIP_REQUEST_ENGAGE_NAVIGATION (6)
#define SHIP_REPLY_ACCEPTED (0)
#define SHIP_REPLY_REJECTED (1)
#define SHIP_REPLY_UNSUPPORTED (2)
#define SHIP_FRAME_SNAPSHOT (0)
#define SHIP_FRAME_SHIP (1)
#define SHIP_FRAME_SHIP_BODY (2)
#define SHIP_FRAME_CONTACT (3)
#define SHIP_FRAME_PATH (4)
#define SHIP_TIME_CURRENT (0)
#define SHIP_TIME_FIXED (1)
#define SHIP_PATH_POLYLINE (0)
#define SHIP_PATH_TIMED (1)
#define SHIP_MARKER_ANNOTATION (0)
#define SHIP_MARKER_TARGET (1)
#define SHIP_MARKER_WAYPOINT (2)
#define SHIP_MARKER_AIM (3)
#define SHIP_MARKER_EVENT (4)
#define SHIP_PATH_REFERENCE (0)
#define SHIP_PATH_OWN_FORECAST (1)
#define SHIP_PATH_CONTACT_FORECAST (2)
#define SHIP_PATH_ROUTE (3)
#define SHIP_ATTITUDE_MANUAL (0)
#define SHIP_ATTITUDE_HOLD (1)
#define SHIP_ATTITUDE_GUIDANCE (2)
#define SHIP_ATTITUDE_REFERENCE (1)
#define SHIP_NAV_IDLE (0)
#define SHIP_NAV_ACTIVE (1)
#define SHIP_NAV_SUSPENDED (2)
#define SHIP_NAV_UNAVAILABLE (3)
#define SHIP_NAV_STAND_OFF (1)
#define SHIP_NAV_SPEED_LIMIT (2)
#define SHIP_NAV_BRAKING_DISTANCE (4)
#define SHIP_NAV_ARRIVAL (8)
#define SHIP_NAV_FUEL (16)
#define SHIP_INSTRUMENT_ATTITUDE (0)
#define SHIP_INSTRUMENT_NAVIGATION (1)
#define SHIP_INSTRUMENT_CONTACTS (2)
#define SHIP_DRAW_PIXEL (0)
#define SHIP_DRAW_TEXT (1)
#define SHIP_DRAW_LINE (2)
#define SHIP_DRAW_POLYLINE (3)
#define SHIP_DRAW_RECTANGLE (4)
#define SHIP_DRAW_ELLIPSE (5)
#define SHIP_EVENT_POINTER_MOVE (0)
#define SHIP_EVENT_POINTER_PRESS (1)
#define SHIP_EVENT_POINTER_RELEASE (2)
#define SHIP_EVENT_KEY_PRESS (3)
#define SHIP_EVENT_TEXT (4)
#define SHIP_EVENT_KEY_RELEASE (5)
#define SHIP_EVENT_BEZEL (6)
#define SHIP_EVENT_RESET (7)
#define SHIP_DEVICE_WEAPON (9)
#define SHIP_DEVICE_RCS (10)
#define SHIP_SET_RCS (6)
#define SHIP_WEAPON_PROPELLANT (4096)
#define SHIP_SET_WEAPON (5)
#define SHIP_REQUEST_MARK_TARGET (7)
#define SHIP_REQUEST_STOP_FIRING (8)
#define SHIP_REQUEST_UNMARK_TARGET (9)
#define SHIP_REQUEST_START_FIRING (10)
#define SHIP_INSTRUMENT_WEAPONS (3)
#define SHIP_CONTACT_PROJECTILE (3)
#define SHIP_WEAPONS_HOLD (0)
#define SHIP_WEAPONS_FIRING (1)
#define SHIP_WEAPON_UNAVAILABLE (1)
#define SHIP_WEAPON_AMMO (4)
#define SHIP_WEAPON_COOLDOWN (16)
#define SHIP_WEAPON_BLOCKED (128)
#define SHIP_WEAPON_TRAVEL (256)
#define SHIP_WEAPON_POINTING (512)
#define SHIP_WEAPON_EXPIRED (1024)
#define SHIP_WEAPON_ENERGY (2048)
#define SHIP_WEAPON_SOLUTION (1)
#define SHIP_WEAPON_ROW_GAS (100)
#define SHIP_SHIELD_ABSENT (0)
#define SHIP_SHIELD_OFF (1)
#define SHIP_SHIELD_ACTIVE (2)
#define SHIP_SHIELD_DEPLETED (3)
#define SHIP_SHIELD_UNPOWERED (4)
#define SHIP_SHIELD_BLOCKED (5)
#define SHIP_DESTINATION_BEACON (0)
#define SHIP_DESTINATION_GALACTIC (1)
#define SHIP_DESTINATION_CELESTIAL_RELATIVE (2)
#define SHIP_DESTINATION_BEACON_RELATIVE (3)
#define SHIP_AXES_GALACTIC (0)
#define SHIP_AXES_BODY_FIXED (1)
#define SHIP_TARGET_DIRECTION (0)
#define SHIP_TARGET_DESTINATION (1)
#define SHIP_TARGET_CONTACT (2)
#define SHIP_ORDER_GUIDANCE (1)
#define SHIP_ORDER_TRAVEL (2)
#define SHIP_ORDER_SUBLIGHT (3)
#define SHIP_ORDER_SLIP (4)
#define SHIP_ORDER_DOCK (5)
#define SHIP_ORDER_UNDOCK (6)
#define SHIP_ORDER_WAIT (7)
#define SHIP_ORDER_TRAVEL_SYSTEM (8)
#define SHIP_GUIDANCE_ALIGN (0)
#define SHIP_GUIDANCE_APPROACH (1)
#define SHIP_GUIDANCE_KEEP_RANGE (2)
#define SHIP_TRAVEL_IDLE (0)
#define SHIP_TRAVEL_PLANNING (1)
#define SHIP_TRAVEL_ACTIVE (2)
#define SHIP_TRAVEL_PAUSED (3)
#define SHIP_TRAVEL_BLOCKED (4)
#define SHIP_TRAVEL_COMPLETED (5)
#define SHIP_ROUTE_UNKNOWN (0)
#define SHIP_ROUTE_PENDING (1)
#define SHIP_ROUTE_READY (2)
#define SHIP_ROUTE_FAILED (3)
#define SHIP_PLANNING_LOADING_CATALOGUE (0)
#define SHIP_PLANNING_BUILDING_GRAPH (1)
#define SHIP_PLANNING_SEARCHING_ROUTES (2)
#define SHIP_LLM_ACCEPTED (0)
#define SHIP_LLM_ALREADY_KNOWN (1)
#define SHIP_LLM_UNAVAILABLE (2)
#define SHIP_LLM_BUSY (3)
#define SHIP_LLM_INSUFFICIENT_GAS (4)
#define SHIP_LLM_INVALID_REQUEST (5)
#define SHIP_CHAT_OWNER_PRESENT (1)
#define SHIP_CHAT_ORGANIZATION_PRESENT (2)
#define SHIP_LLM_UNKNOWN (0)
#define SHIP_LLM_PENDING (1)
#define SHIP_LLM_READY (2)
#define SHIP_LLM_FAILED (3)
#define SHIP_LLM_CANCELLED (4)
#define SHIP_LLM_INDETERMINATE (5)
typedef struct { uint64_t len; uint8_t bytes[64]; } ship_text64;
SHIP_ASSERT(sizeof(ship_text64) == 72, "text layout");
SHIP_ASSERT(SHIP_ALIGNOF(ship_text64) == 8, "text alignment");
typedef struct { uint64_t len; uint8_t bytes[256]; } ship_text256;
SHIP_ASSERT(sizeof(ship_text256) == 264, "text layout");
SHIP_ASSERT(SHIP_ALIGNOF(ship_text256) == 8, "text alignment");
typedef struct {
    double throttle;
} ship_throttle_request_record;
SHIP_ASSERT(offsetof(ship_throttle_request_record, throttle) == 0, "ThrottleRequest.throttle");
SHIP_ASSERT(sizeof(ship_throttle_request_record) == 8, "ThrottleRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_throttle_request_record) == 8, "ThrottleRequest alignment");
typedef struct {
    uint64_t tick;
    uint64_t snapshot;
    double time_s;
    double dt_s;
    double physics_dt_s;
    uint64_t device_count;
    uint64_t resource_count;
    uint64_t request_count;
    uint64_t screen_event_count;
    uint64_t interest;
    uint64_t requested_screens;
    uint64_t flags;
} ship_tick_context_record;
SHIP_ASSERT(offsetof(ship_tick_context_record, tick) == 0, "TickContext.tick");
SHIP_ASSERT(offsetof(ship_tick_context_record, snapshot) == 8, "TickContext.snapshot");
SHIP_ASSERT(offsetof(ship_tick_context_record, time_s) == 16, "TickContext.time_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, dt_s) == 24, "TickContext.dt_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, physics_dt_s) == 32, "TickContext.physics_dt_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, device_count) == 40, "TickContext.device_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, resource_count) == 48, "TickContext.resource_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, request_count) == 56, "TickContext.request_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, screen_event_count) == 64, "TickContext.screen_event_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, interest) == 72, "TickContext.interest");
SHIP_ASSERT(offsetof(ship_tick_context_record, requested_screens) == 80, "TickContext.requested_screens");
SHIP_ASSERT(offsetof(ship_tick_context_record, flags) == 88, "TickContext.flags");
SHIP_ASSERT(sizeof(ship_tick_context_record) == 96, "TickContext size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_tick_context_record) == 8, "TickContext alignment");
typedef struct {
    uint64_t gas_remaining;
    uint64_t gas_limit;
    uint64_t gas_per_tick;
} ship_budget_info_record;
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_remaining) == 0, "BudgetInfo.gas_remaining");
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_limit) == 8, "BudgetInfo.gas_limit");
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_per_tick) == 16, "BudgetInfo.gas_per_tick");
SHIP_ASSERT(sizeof(ship_budget_info_record) == 24, "BudgetInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_budget_info_record) == 8, "BudgetInfo alignment");
typedef struct {
    double rotation[4];
    double angular_velocity[3];
    double velocity[3];
    double mass_kg;
    double inertia[9];
    double radius_m;
} ship_flight_state_record;
SHIP_ASSERT(offsetof(ship_flight_state_record, rotation) == 0, "FlightState.rotation");
SHIP_ASSERT(offsetof(ship_flight_state_record, angular_velocity) == 32, "FlightState.angular_velocity");
SHIP_ASSERT(offsetof(ship_flight_state_record, velocity) == 56, "FlightState.velocity");
SHIP_ASSERT(offsetof(ship_flight_state_record, mass_kg) == 80, "FlightState.mass_kg");
SHIP_ASSERT(offsetof(ship_flight_state_record, inertia) == 88, "FlightState.inertia");
SHIP_ASSERT(offsetof(ship_flight_state_record, radius_m) == 160, "FlightState.radius_m");
SHIP_ASSERT(sizeof(ship_flight_state_record) == 168, "FlightState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_flight_state_record) == 8, "FlightState alignment");
typedef struct {
    double hull_hp;
    double hull_max_hp;
    double hull_heat_j;
    double hull_heat_capacity_j;
    double shield_temperature_k;
    double shield_reserve_kg;
    double shield_reserve_capacity_kg;
    double shield_strength;
    uint64_t energy_j;
    uint64_t shield_state;
} ship_ship_resources_record;
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_hp) == 0, "ShipResources.hull_hp");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_max_hp) == 8, "ShipResources.hull_max_hp");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_heat_j) == 16, "ShipResources.hull_heat_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_heat_capacity_j) == 24, "ShipResources.hull_heat_capacity_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_temperature_k) == 32, "ShipResources.shield_temperature_k");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_reserve_kg) == 40, "ShipResources.shield_reserve_kg");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_reserve_capacity_kg) == 48, "ShipResources.shield_reserve_capacity_kg");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_strength) == 56, "ShipResources.shield_strength");
SHIP_ASSERT(offsetof(ship_ship_resources_record, energy_j) == 64, "ShipResources.energy_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_state) == 72, "ShipResources.shield_state");
SHIP_ASSERT(sizeof(ship_ship_resources_record) == 80, "ShipResources size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_ship_resources_record) == 8, "ShipResources alignment");
typedef struct {
    uint64_t id;
    uint64_t part_id;
    uint64_t kind;
    uint64_t flags;
    double position_m[3];
    double rotation[4];
    ship_text64 alias;
    uint64_t group_count;
} ship_device_info_record;
SHIP_ASSERT(offsetof(ship_device_info_record, id) == 0, "DeviceInfo.id");
SHIP_ASSERT(offsetof(ship_device_info_record, part_id) == 8, "DeviceInfo.part_id");
SHIP_ASSERT(offsetof(ship_device_info_record, kind) == 16, "DeviceInfo.kind");
SHIP_ASSERT(offsetof(ship_device_info_record, flags) == 24, "DeviceInfo.flags");
SHIP_ASSERT(offsetof(ship_device_info_record, position_m) == 32, "DeviceInfo.position_m");
SHIP_ASSERT(offsetof(ship_device_info_record, rotation) == 56, "DeviceInfo.rotation");
SHIP_ASSERT(offsetof(ship_device_info_record, alias) == 88, "DeviceInfo.alias");
SHIP_ASSERT(offsetof(ship_device_info_record, group_count) == 160, "DeviceInfo.group_count");
SHIP_ASSERT(sizeof(ship_device_info_record) == 168, "DeviceInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_device_info_record) == 8, "DeviceInfo alignment");
typedef struct {
    uint64_t flags;
} ship_device_status_record;
SHIP_ASSERT(offsetof(ship_device_status_record, flags) == 0, "DeviceStatus.flags");
SHIP_ASSERT(sizeof(ship_device_status_record) == 8, "DeviceStatus size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_device_status_record) == 8, "DeviceStatus alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t sample_present;
    double sample_time_s;
    double acceleration[3];
} ship_accelerometer_reading_record;
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, status) == 0, "AccelerometerReading.status");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, sample_present) == 8, "AccelerometerReading.sample_present");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, sample_time_s) == 16, "AccelerometerReading.sample_time_s");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, acceleration) == 24, "AccelerometerReading.acceleration");
SHIP_ASSERT(sizeof(ship_accelerometer_reading_record) == 48, "AccelerometerReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_accelerometer_reading_record) == 8, "AccelerometerReading alignment");
typedef struct {
    double capacity_m3;
} ship_storage_spec_record;
SHIP_ASSERT(offsetof(ship_storage_spec_record, capacity_m3) == 0, "StorageSpec.capacity_m3");
SHIP_ASSERT(sizeof(ship_storage_spec_record) == 8, "StorageSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_storage_spec_record) == 8, "StorageSpec alignment");
typedef struct {
    uint64_t capacity_j;
} ship_battery_spec_record;
SHIP_ASSERT(offsetof(ship_battery_spec_record, capacity_j) == 0, "BatterySpec.capacity_j");
SHIP_ASSERT(sizeof(ship_battery_spec_record) == 8, "BatterySpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_battery_spec_record) == 8, "BatterySpec alignment");
typedef struct {
    uint64_t propellant_resource;
    double max_thrust_n;
    double propellant_units_s;
    double max_power_w;
} ship_engine_spec_record;
SHIP_ASSERT(offsetof(ship_engine_spec_record, propellant_resource) == 0, "EngineSpec.propellant_resource");
SHIP_ASSERT(offsetof(ship_engine_spec_record, max_thrust_n) == 8, "EngineSpec.max_thrust_n");
SHIP_ASSERT(offsetof(ship_engine_spec_record, propellant_units_s) == 16, "EngineSpec.propellant_units_s");
SHIP_ASSERT(offsetof(ship_engine_spec_record, max_power_w) == 24, "EngineSpec.max_power_w");
SHIP_ASSERT(sizeof(ship_engine_spec_record) == 32, "EngineSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_engine_spec_record) == 8, "EngineSpec alignment");
typedef struct {
    ship_device_status_record status;
    double thrust_n;
} ship_engine_reading_record;
SHIP_ASSERT(offsetof(ship_engine_reading_record, status) == 0, "EngineReading.status");
SHIP_ASSERT(offsetof(ship_engine_reading_record, thrust_n) == 8, "EngineReading.thrust_n");
SHIP_ASSERT(sizeof(ship_engine_reading_record) == 16, "EngineReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_engine_reading_record) == 8, "EngineReading alignment");
typedef struct {
    double per_axis_limit_nm;
    double max_power_w;
} ship_torquer_spec_record;
SHIP_ASSERT(offsetof(ship_torquer_spec_record, per_axis_limit_nm) == 0, "TorquerSpec.per_axis_limit_nm");
SHIP_ASSERT(offsetof(ship_torquer_spec_record, max_power_w) == 8, "TorquerSpec.max_power_w");
SHIP_ASSERT(sizeof(ship_torquer_spec_record) == 16, "TorquerSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torquer_spec_record) == 8, "TorquerSpec alignment");
typedef struct {
    ship_device_status_record status;
    double torque_magnitude_nm;
} ship_torquer_reading_record;
SHIP_ASSERT(offsetof(ship_torquer_reading_record, status) == 0, "TorquerReading.status");
SHIP_ASSERT(offsetof(ship_torquer_reading_record, torque_magnitude_nm) == 8, "TorquerReading.torque_magnitude_nm");
SHIP_ASSERT(sizeof(ship_torquer_reading_record) == 16, "TorquerReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torquer_reading_record) == 8, "TorquerReading alignment");
typedef struct {
    uint64_t fuel_resource;
    double max_power_w;
    double fuel_units_s;
    double efficiency;
} ship_generator_spec_record;
SHIP_ASSERT(offsetof(ship_generator_spec_record, fuel_resource) == 0, "GeneratorSpec.fuel_resource");
SHIP_ASSERT(offsetof(ship_generator_spec_record, max_power_w) == 8, "GeneratorSpec.max_power_w");
SHIP_ASSERT(offsetof(ship_generator_spec_record, fuel_units_s) == 16, "GeneratorSpec.fuel_units_s");
SHIP_ASSERT(offsetof(ship_generator_spec_record, efficiency) == 24, "GeneratorSpec.efficiency");
SHIP_ASSERT(sizeof(ship_generator_spec_record) == 32, "GeneratorSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_spec_record) == 8, "GeneratorSpec alignment");
typedef struct {
    ship_device_status_record status;
    double power_w;
} ship_generator_reading_record;
SHIP_ASSERT(offsetof(ship_generator_reading_record, status) == 0, "GeneratorReading.status");
SHIP_ASSERT(offsetof(ship_generator_reading_record, power_w) == 8, "GeneratorReading.power_w");
SHIP_ASSERT(sizeof(ship_generator_reading_record) == 16, "GeneratorReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_reading_record) == 8, "GeneratorReading alignment");
typedef struct {
    double deployed_mass_kg;
    double radiator_area_m2;
    double feed_rate_kg_s;
    double emissivity;
    double sustain_power_w;
} ship_shield_spec_record;
SHIP_ASSERT(offsetof(ship_shield_spec_record, deployed_mass_kg) == 0, "ShieldSpec.deployed_mass_kg");
SHIP_ASSERT(offsetof(ship_shield_spec_record, radiator_area_m2) == 8, "ShieldSpec.radiator_area_m2");
SHIP_ASSERT(offsetof(ship_shield_spec_record, feed_rate_kg_s) == 16, "ShieldSpec.feed_rate_kg_s");
SHIP_ASSERT(offsetof(ship_shield_spec_record, emissivity) == 24, "ShieldSpec.emissivity");
SHIP_ASSERT(offsetof(ship_shield_spec_record, sustain_power_w) == 32, "ShieldSpec.sustain_power_w");
SHIP_ASSERT(sizeof(ship_shield_spec_record) == 40, "ShieldSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_shield_spec_record) == 8, "ShieldSpec alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t state;
    double temperature_k;
    double reserve_kg;
    double reserve_capacity_kg;
    double strength;
    double ablation_kg_s;
    double radiated_power_w;
    double power_w;
} ship_shield_reading_record;
SHIP_ASSERT(offsetof(ship_shield_reading_record, status) == 0, "ShieldReading.status");
SHIP_ASSERT(offsetof(ship_shield_reading_record, state) == 8, "ShieldReading.state");
SHIP_ASSERT(offsetof(ship_shield_reading_record, temperature_k) == 16, "ShieldReading.temperature_k");
SHIP_ASSERT(offsetof(ship_shield_reading_record, reserve_kg) == 24, "ShieldReading.reserve_kg");
SHIP_ASSERT(offsetof(ship_shield_reading_record, reserve_capacity_kg) == 32, "ShieldReading.reserve_capacity_kg");
SHIP_ASSERT(offsetof(ship_shield_reading_record, strength) == 40, "ShieldReading.strength");
SHIP_ASSERT(offsetof(ship_shield_reading_record, ablation_kg_s) == 48, "ShieldReading.ablation_kg_s");
SHIP_ASSERT(offsetof(ship_shield_reading_record, radiated_power_w) == 56, "ShieldReading.radiated_power_w");
SHIP_ASSERT(offsetof(ship_shield_reading_record, power_w) == 64, "ShieldReading.power_w");
SHIP_ASSERT(sizeof(ship_shield_reading_record) == 72, "ShieldReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_shield_reading_record) == 8, "ShieldReading alignment");
typedef struct {
    uint64_t ammunition_resource;
    double projectile_mass_kg;
    double projectile_radius_m;
    double muzzle_speed_m_s;
    double cycle_interval_s;
    double efficiency;
    double dispersion_half_angle_rad;
    double pivot_device_m[3];
    double muzzle_offset_m[3];
    double yaw_min_rad;
    double yaw_max_rad;
    double pitch_min_rad;
    double pitch_max_rad;
    double yaw_rate_rad_s;
    double pitch_rate_rad_s;
    double beam_power_w;
    double beam_range_m;
    uint64_t chemical;
} ship_weapon_spec_record;
SHIP_ASSERT(offsetof(ship_weapon_spec_record, ammunition_resource) == 0, "WeaponSpec.ammunition_resource");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, projectile_mass_kg) == 8, "WeaponSpec.projectile_mass_kg");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, projectile_radius_m) == 16, "WeaponSpec.projectile_radius_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, muzzle_speed_m_s) == 24, "WeaponSpec.muzzle_speed_m_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, cycle_interval_s) == 32, "WeaponSpec.cycle_interval_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, efficiency) == 40, "WeaponSpec.efficiency");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, dispersion_half_angle_rad) == 48, "WeaponSpec.dispersion_half_angle_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pivot_device_m) == 56, "WeaponSpec.pivot_device_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, muzzle_offset_m) == 80, "WeaponSpec.muzzle_offset_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_min_rad) == 104, "WeaponSpec.yaw_min_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_max_rad) == 112, "WeaponSpec.yaw_max_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_min_rad) == 120, "WeaponSpec.pitch_min_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_max_rad) == 128, "WeaponSpec.pitch_max_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_rate_rad_s) == 136, "WeaponSpec.yaw_rate_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_rate_rad_s) == 144, "WeaponSpec.pitch_rate_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, beam_power_w) == 152, "WeaponSpec.beam_power_w");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, beam_range_m) == 160, "WeaponSpec.beam_range_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, chemical) == 168, "WeaponSpec.chemical");
SHIP_ASSERT(sizeof(ship_weapon_spec_record) == 176, "WeaponSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_spec_record) == 8, "WeaponSpec alignment");
typedef struct {
    double aim_direction[3];
    double aim_angular_velocity_rad_s[3];
    double maximum_pointing_error_rad;
    double valid_until_s;
    uint64_t trigger;
} ship_weapon_setting_record;
SHIP_ASSERT(offsetof(ship_weapon_setting_record, aim_direction) == 0, "WeaponSetting.aim_direction");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, aim_angular_velocity_rad_s) == 24, "WeaponSetting.aim_angular_velocity_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, maximum_pointing_error_rad) == 48, "WeaponSetting.maximum_pointing_error_rad");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, valid_until_s) == 56, "WeaponSetting.valid_until_s");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, trigger) == 64, "WeaponSetting.trigger");
SHIP_ASSERT(sizeof(ship_weapon_setting_record) == 72, "WeaponSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_setting_record) == 8, "WeaponSetting alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t inhibit_flags;
    uint64_t ammunition_units;
    uint64_t shots_fired;
    uint64_t battery_energy_j;
    double shot_energy_j;
    double yaw_rad;
    double pitch_rad;
    double next_fire_s;
} ship_weapon_reading_record;
SHIP_ASSERT(offsetof(ship_weapon_reading_record, status) == 0, "WeaponReading.status");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, inhibit_flags) == 8, "WeaponReading.inhibit_flags");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, ammunition_units) == 16, "WeaponReading.ammunition_units");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, shots_fired) == 24, "WeaponReading.shots_fired");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, battery_energy_j) == 32, "WeaponReading.battery_energy_j");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, shot_energy_j) == 40, "WeaponReading.shot_energy_j");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, yaw_rad) == 48, "WeaponReading.yaw_rad");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, pitch_rad) == 56, "WeaponReading.pitch_rad");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, next_fire_s) == 64, "WeaponReading.next_fire_s");
SHIP_ASSERT(sizeof(ship_weapon_reading_record) == 72, "WeaponReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_reading_record) == 8, "WeaponReading alignment");
typedef struct {
    uint64_t contact;
    double maximum_flight_time_s;
} ship_mark_target_request_record;
SHIP_ASSERT(offsetof(ship_mark_target_request_record, contact) == 0, "MarkTargetRequest.contact");
SHIP_ASSERT(offsetof(ship_mark_target_request_record, maximum_flight_time_s) == 8, "MarkTargetRequest.maximum_flight_time_s");
SHIP_ASSERT(sizeof(ship_mark_target_request_record) == 16, "MarkTargetRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_mark_target_request_record) == 8, "MarkTargetRequest alignment");
typedef struct {
    double valid_until_s;
    uint64_t mode;
    uint64_t target_contact;
    ship_text256 reason;
} ship_weapons_state_record;
SHIP_ASSERT(offsetof(ship_weapons_state_record, valid_until_s) == 0, "WeaponsState.valid_until_s");
SHIP_ASSERT(offsetof(ship_weapons_state_record, mode) == 8, "WeaponsState.mode");
SHIP_ASSERT(offsetof(ship_weapons_state_record, target_contact) == 16, "WeaponsState.target_contact");
SHIP_ASSERT(offsetof(ship_weapons_state_record, reason) == 24, "WeaponsState.reason");
SHIP_ASSERT(sizeof(ship_weapons_state_record) == 288, "WeaponsState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapons_state_record) == 8, "WeaponsState alignment");
typedef struct {
    uint64_t device;
    uint64_t aim_marker;
    uint64_t solution_flags;
    double time_of_flight_s;
    double pointing_error_rad;
    ship_weapon_reading_record reading;
} ship_weapon_instrument_record;
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, device) == 0, "WeaponInstrument.device");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, aim_marker) == 8, "WeaponInstrument.aim_marker");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, solution_flags) == 16, "WeaponInstrument.solution_flags");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, time_of_flight_s) == 24, "WeaponInstrument.time_of_flight_s");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, pointing_error_rad) == 32, "WeaponInstrument.pointing_error_rad");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, reading) == 40, "WeaponInstrument.reading");
SHIP_ASSERT(sizeof(ship_weapon_instrument_record) == 112, "WeaponInstrument size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_instrument_record) == 8, "WeaponInstrument alignment");
typedef struct {
    double max_range_m;
    double power_w;
} ship_sensor_spec_record;
SHIP_ASSERT(offsetof(ship_sensor_spec_record, max_range_m) == 0, "SensorSpec.max_range_m");
SHIP_ASSERT(offsetof(ship_sensor_spec_record, power_w) == 8, "SensorSpec.power_w");
SHIP_ASSERT(sizeof(ship_sensor_spec_record) == 16, "SensorSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_sensor_spec_record) == 8, "SensorSpec alignment");
typedef struct {
    ship_device_status_record status;
    double range_m;
} ship_sensor_reading_record;
SHIP_ASSERT(offsetof(ship_sensor_reading_record, status) == 0, "SensorReading.status");
SHIP_ASSERT(offsetof(ship_sensor_reading_record, range_m) == 8, "SensorReading.range_m");
SHIP_ASSERT(sizeof(ship_sensor_reading_record) == 16, "SensorReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_sensor_reading_record) == 8, "SensorReading alignment");
typedef struct {
    double fraction;
} ship_throttle_setting_record;
SHIP_ASSERT(offsetof(ship_throttle_setting_record, fraction) == 0, "ThrottleSetting.fraction");
SHIP_ASSERT(sizeof(ship_throttle_setting_record) == 8, "ThrottleSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_throttle_setting_record) == 8, "ThrottleSetting alignment");
typedef struct {
    double torque_nm[3];
} ship_torque_setting_record;
SHIP_ASSERT(offsetof(ship_torque_setting_record, torque_nm) == 0, "TorqueSetting.torque_nm");
SHIP_ASSERT(sizeof(ship_torque_setting_record) == 24, "TorqueSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torque_setting_record) == 8, "TorqueSetting alignment");
typedef struct {
    double fraction;
} ship_generator_demand_setting_record;
SHIP_ASSERT(offsetof(ship_generator_demand_setting_record, fraction) == 0, "GeneratorDemandSetting.fraction");
SHIP_ASSERT(sizeof(ship_generator_demand_setting_record) == 8, "GeneratorDemandSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_demand_setting_record) == 8, "GeneratorDemandSetting alignment");
typedef struct {
    uint64_t enabled;
} ship_enabled_setting_record;
SHIP_ASSERT(offsetof(ship_enabled_setting_record, enabled) == 0, "EnabledSetting.enabled");
SHIP_ASSERT(sizeof(ship_enabled_setting_record) == 8, "EnabledSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_enabled_setting_record) == 8, "EnabledSetting alignment");
typedef struct {
    uint64_t id;
    ship_text64 key;
    double unit_mass_kg;
    double unit_volume_m3;
} ship_resource_info_record;
SHIP_ASSERT(offsetof(ship_resource_info_record, id) == 0, "ResourceInfo.id");
SHIP_ASSERT(offsetof(ship_resource_info_record, key) == 8, "ResourceInfo.key");
SHIP_ASSERT(offsetof(ship_resource_info_record, unit_mass_kg) == 80, "ResourceInfo.unit_mass_kg");
SHIP_ASSERT(offsetof(ship_resource_info_record, unit_volume_m3) == 88, "ResourceInfo.unit_volume_m3");
SHIP_ASSERT(sizeof(ship_resource_info_record) == 96, "ResourceInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_resource_info_record) == 8, "ResourceInfo alignment");
typedef struct {
    uint64_t units;
} ship_resource_amount_record;
SHIP_ASSERT(offsetof(ship_resource_amount_record, units) == 0, "ResourceAmount.units");
SHIP_ASSERT(sizeof(ship_resource_amount_record) == 8, "ResourceAmount size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_resource_amount_record) == 8, "ResourceAmount alignment");
typedef struct {
    uint64_t id;
    uint64_t kind;
    double radius_m;
    double position_m[3];
    double velocity_m_s[3];
} ship_contact_record;
SHIP_ASSERT(offsetof(ship_contact_record, id) == 0, "Contact.id");
SHIP_ASSERT(offsetof(ship_contact_record, kind) == 8, "Contact.kind");
SHIP_ASSERT(offsetof(ship_contact_record, radius_m) == 16, "Contact.radius_m");
SHIP_ASSERT(offsetof(ship_contact_record, position_m) == 24, "Contact.position_m");
SHIP_ASSERT(offsetof(ship_contact_record, velocity_m_s) == 48, "Contact.velocity_m_s");
SHIP_ASSERT(sizeof(ship_contact_record) == 72, "Contact size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_record) == 8, "Contact alignment");
typedef struct {
    uint64_t id;
    uint64_t kind;
    uint64_t payload_bytes;
} ship_request_info_record;
SHIP_ASSERT(offsetof(ship_request_info_record, id) == 0, "RequestInfo.id");
SHIP_ASSERT(offsetof(ship_request_info_record, kind) == 8, "RequestInfo.kind");
SHIP_ASSERT(offsetof(ship_request_info_record, payload_bytes) == 16, "RequestInfo.payload_bytes");
SHIP_ASSERT(sizeof(ship_request_info_record) == 24, "RequestInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_request_info_record) == 8, "RequestInfo alignment");
typedef struct {
    double throttle;
    double steering[3];
} ship_manual_request_record;
SHIP_ASSERT(offsetof(ship_manual_request_record, throttle) == 0, "ManualRequest.throttle");
SHIP_ASSERT(offsetof(ship_manual_request_record, steering) == 8, "ManualRequest.steering");
SHIP_ASSERT(sizeof(ship_manual_request_record) == 32, "ManualRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_manual_request_record) == 8, "ManualRequest alignment");
typedef struct {
    double direction[3];
} ship_direction_request_record;
SHIP_ASSERT(offsetof(ship_direction_request_record, direction) == 0, "DirectionRequest.direction");
SHIP_ASSERT(sizeof(ship_direction_request_record) == 24, "DirectionRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_direction_request_record) == 8, "DirectionRequest alignment");
typedef struct {
    uint64_t contact;
} ship_contact_request_record;
SHIP_ASSERT(offsetof(ship_contact_request_record, contact) == 0, "ContactRequest.contact");
SHIP_ASSERT(sizeof(ship_contact_request_record) == 8, "ContactRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_request_record) == 8, "ContactRequest alignment");
typedef struct {
    double throttle_limit;
    double stand_off_m;
} ship_navigation_request_record;
SHIP_ASSERT(offsetof(ship_navigation_request_record, throttle_limit) == 0, "NavigationRequest.throttle_limit");
SHIP_ASSERT(offsetof(ship_navigation_request_record, stand_off_m) == 8, "NavigationRequest.stand_off_m");
SHIP_ASSERT(sizeof(ship_navigation_request_record) == 16, "NavigationRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_navigation_request_record) == 8, "NavigationRequest alignment");
typedef struct {
    uint64_t id;
    uint64_t role;
    double valid_until_s;
    ship_text64 label;
} ship_spatial_meta_record;
SHIP_ASSERT(offsetof(ship_spatial_meta_record, id) == 0, "SpatialMeta.id");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, role) == 8, "SpatialMeta.role");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, valid_until_s) == 16, "SpatialMeta.valid_until_s");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, label) == 24, "SpatialMeta.label");
SHIP_ASSERT(sizeof(ship_spatial_meta_record) == 96, "SpatialMeta size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_meta_record) == 8, "SpatialMeta alignment");
typedef struct {
    uint64_t kind;
    uint64_t reference;
    double origin_velocity_m_s[3];
} ship_spatial_frame_record;
SHIP_ASSERT(offsetof(ship_spatial_frame_record, kind) == 0, "SpatialFrame.kind");
SHIP_ASSERT(offsetof(ship_spatial_frame_record, reference) == 8, "SpatialFrame.reference");
SHIP_ASSERT(offsetof(ship_spatial_frame_record, origin_velocity_m_s) == 16, "SpatialFrame.origin_velocity_m_s");
SHIP_ASSERT(sizeof(ship_spatial_frame_record) == 40, "SpatialFrame size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_frame_record) == 8, "SpatialFrame alignment");
typedef struct {
    ship_spatial_meta_record meta;
    ship_spatial_frame_record frame;
    double offset_m[3];
    uint64_t time_mode;
    double time_s;
} ship_spatial_marker_record;
SHIP_ASSERT(offsetof(ship_spatial_marker_record, meta) == 0, "SpatialMarker.meta");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, frame) == 96, "SpatialMarker.frame");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, offset_m) == 136, "SpatialMarker.offset_m");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, time_mode) == 160, "SpatialMarker.time_mode");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, time_s) == 168, "SpatialMarker.time_s");
SHIP_ASSERT(sizeof(ship_spatial_marker_record) == 176, "SpatialMarker size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_marker_record) == 8, "SpatialMarker alignment");
typedef struct {
    ship_spatial_meta_record meta;
    ship_spatial_frame_record frame;
    uint64_t kind;
    uint64_t subject_contact;
} ship_spatial_path_record;
SHIP_ASSERT(offsetof(ship_spatial_path_record, meta) == 0, "SpatialPath.meta");
SHIP_ASSERT(offsetof(ship_spatial_path_record, frame) == 96, "SpatialPath.frame");
SHIP_ASSERT(offsetof(ship_spatial_path_record, kind) == 136, "SpatialPath.kind");
SHIP_ASSERT(offsetof(ship_spatial_path_record, subject_contact) == 144, "SpatialPath.subject_contact");
SHIP_ASSERT(sizeof(ship_spatial_path_record) == 152, "SpatialPath size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_path_record) == 8, "SpatialPath alignment");
typedef struct {
    double time_s;
    double position_m[3];
} ship_spatial_vertex_record;
SHIP_ASSERT(offsetof(ship_spatial_vertex_record, time_s) == 0, "SpatialVertex.time_s");
SHIP_ASSERT(offsetof(ship_spatial_vertex_record, position_m) == 8, "SpatialVertex.position_m");
SHIP_ASSERT(sizeof(ship_spatial_vertex_record) == 32, "SpatialVertex size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_vertex_record) == 8, "SpatialVertex alignment");
typedef struct {
    double valid_until_s;
    uint64_t mode;
    uint64_t present;
    double reference[4];
    double control_error;
} ship_attitude_state_record;
SHIP_ASSERT(offsetof(ship_attitude_state_record, valid_until_s) == 0, "AttitudeState.valid_until_s");
SHIP_ASSERT(offsetof(ship_attitude_state_record, mode) == 8, "AttitudeState.mode");
SHIP_ASSERT(offsetof(ship_attitude_state_record, present) == 16, "AttitudeState.present");
SHIP_ASSERT(offsetof(ship_attitude_state_record, reference) == 24, "AttitudeState.reference");
SHIP_ASSERT(offsetof(ship_attitude_state_record, control_error) == 56, "AttitudeState.control_error");
SHIP_ASSERT(sizeof(ship_attitude_state_record) == 64, "AttitudeState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_attitude_state_record) == 8, "AttitudeState alignment");
typedef struct {
    double valid_until_s;
    uint64_t status;
    uint64_t target_contact;
    uint64_t own_path;
    uint64_t target_path;
    uint64_t present;
    double throttle_limit;
    double throttle;
    double stand_off_m;
    double approach_speed_limit_m_s;
    double braking_distance_m;
    double arrival_time_s;
    double predicted_fuel_kg;
    ship_text256 reason;
} ship_navigation_state_record;
SHIP_ASSERT(offsetof(ship_navigation_state_record, valid_until_s) == 0, "NavigationState.valid_until_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, status) == 8, "NavigationState.status");
SHIP_ASSERT(offsetof(ship_navigation_state_record, target_contact) == 16, "NavigationState.target_contact");
SHIP_ASSERT(offsetof(ship_navigation_state_record, own_path) == 24, "NavigationState.own_path");
SHIP_ASSERT(offsetof(ship_navigation_state_record, target_path) == 32, "NavigationState.target_path");
SHIP_ASSERT(offsetof(ship_navigation_state_record, present) == 40, "NavigationState.present");
SHIP_ASSERT(offsetof(ship_navigation_state_record, throttle_limit) == 48, "NavigationState.throttle_limit");
SHIP_ASSERT(offsetof(ship_navigation_state_record, throttle) == 56, "NavigationState.throttle");
SHIP_ASSERT(offsetof(ship_navigation_state_record, stand_off_m) == 64, "NavigationState.stand_off_m");
SHIP_ASSERT(offsetof(ship_navigation_state_record, approach_speed_limit_m_s) == 72, "NavigationState.approach_speed_limit_m_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, braking_distance_m) == 80, "NavigationState.braking_distance_m");
SHIP_ASSERT(offsetof(ship_navigation_state_record, arrival_time_s) == 88, "NavigationState.arrival_time_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, predicted_fuel_kg) == 96, "NavigationState.predicted_fuel_kg");
SHIP_ASSERT(offsetof(ship_navigation_state_record, reason) == 104, "NavigationState.reason");
SHIP_ASSERT(sizeof(ship_navigation_state_record) == 368, "NavigationState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_navigation_state_record) == 8, "NavigationState alignment");
typedef struct {
    double valid_until_s;
    uint64_t selected_contact;
} ship_contacts_state_record;
SHIP_ASSERT(offsetof(ship_contacts_state_record, valid_until_s) == 0, "ContactsState.valid_until_s");
SHIP_ASSERT(offsetof(ship_contacts_state_record, selected_contact) == 8, "ContactsState.selected_contact");
SHIP_ASSERT(sizeof(ship_contacts_state_record) == 16, "ContactsState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contacts_state_record) == 8, "ContactsState alignment");
typedef struct {
    uint64_t id;
    uint64_t width;
    uint64_t height;
    ship_text64 title;
} ship_screen_definition_record;
SHIP_ASSERT(offsetof(ship_screen_definition_record, id) == 0, "ScreenDefinition.id");
SHIP_ASSERT(offsetof(ship_screen_definition_record, width) == 8, "ScreenDefinition.width");
SHIP_ASSERT(offsetof(ship_screen_definition_record, height) == 16, "ScreenDefinition.height");
SHIP_ASSERT(offsetof(ship_screen_definition_record, title) == 24, "ScreenDefinition.title");
SHIP_ASSERT(sizeof(ship_screen_definition_record) == 96, "ScreenDefinition size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_definition_record) == 8, "ScreenDefinition alignment");
typedef struct {
    uint64_t id;
    uint64_t background;
} ship_screen_frame_record;
SHIP_ASSERT(offsetof(ship_screen_frame_record, id) == 0, "ScreenFrame.id");
SHIP_ASSERT(offsetof(ship_screen_frame_record, background) == 8, "ScreenFrame.background");
SHIP_ASSERT(sizeof(ship_screen_frame_record) == 16, "ScreenFrame size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_frame_record) == 8, "ScreenFrame alignment");
typedef struct {
    uint64_t color;
    int64_t x;
    int64_t y;
} ship_screen_pixel_record;
SHIP_ASSERT(offsetof(ship_screen_pixel_record, color) == 0, "ScreenPixel.color");
SHIP_ASSERT(offsetof(ship_screen_pixel_record, x) == 8, "ScreenPixel.x");
SHIP_ASSERT(offsetof(ship_screen_pixel_record, y) == 16, "ScreenPixel.y");
SHIP_ASSERT(sizeof(ship_screen_pixel_record) == 24, "ScreenPixel size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_pixel_record) == 8, "ScreenPixel alignment");
typedef struct {
    uint64_t color;
    int64_t x;
    int64_t y;
} ship_screen_text_record;
SHIP_ASSERT(offsetof(ship_screen_text_record, color) == 0, "ScreenText.color");
SHIP_ASSERT(offsetof(ship_screen_text_record, x) == 8, "ScreenText.x");
SHIP_ASSERT(offsetof(ship_screen_text_record, y) == 16, "ScreenText.y");
SHIP_ASSERT(sizeof(ship_screen_text_record) == 24, "ScreenText size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_text_record) == 8, "ScreenText alignment");
typedef struct {
    uint64_t color;
    int64_t x1;
    int64_t y1;
    int64_t x2;
    int64_t y2;
} ship_screen_line_record;
SHIP_ASSERT(offsetof(ship_screen_line_record, color) == 0, "ScreenLine.color");
SHIP_ASSERT(offsetof(ship_screen_line_record, x1) == 8, "ScreenLine.x1");
SHIP_ASSERT(offsetof(ship_screen_line_record, y1) == 16, "ScreenLine.y1");
SHIP_ASSERT(offsetof(ship_screen_line_record, x2) == 24, "ScreenLine.x2");
SHIP_ASSERT(offsetof(ship_screen_line_record, y2) == 32, "ScreenLine.y2");
SHIP_ASSERT(sizeof(ship_screen_line_record) == 40, "ScreenLine size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_line_record) == 8, "ScreenLine alignment");
typedef struct {
    uint64_t color;
} ship_screen_polyline_record;
SHIP_ASSERT(offsetof(ship_screen_polyline_record, color) == 0, "ScreenPolyline.color");
SHIP_ASSERT(sizeof(ship_screen_polyline_record) == 8, "ScreenPolyline size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_polyline_record) == 8, "ScreenPolyline alignment");
typedef struct {
    int64_t x;
    int64_t y;
} ship_screen_point_record;
SHIP_ASSERT(offsetof(ship_screen_point_record, x) == 0, "ScreenPoint.x");
SHIP_ASSERT(offsetof(ship_screen_point_record, y) == 8, "ScreenPoint.y");
SHIP_ASSERT(sizeof(ship_screen_point_record) == 16, "ScreenPoint size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_point_record) == 8, "ScreenPoint alignment");
typedef struct {
    uint64_t color;
    uint64_t filled;
    int64_t x;
    int64_t y;
    uint64_t width;
    uint64_t height;
} ship_screen_rectangle_record;
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, color) == 0, "ScreenRectangle.color");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, filled) == 8, "ScreenRectangle.filled");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, x) == 16, "ScreenRectangle.x");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, y) == 24, "ScreenRectangle.y");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, width) == 32, "ScreenRectangle.width");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, height) == 40, "ScreenRectangle.height");
SHIP_ASSERT(sizeof(ship_screen_rectangle_record) == 48, "ScreenRectangle size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_rectangle_record) == 8, "ScreenRectangle alignment");
typedef struct {
    uint64_t color;
    uint64_t filled;
    int64_t cx;
    int64_t cy;
    uint64_t rx;
    uint64_t ry;
} ship_screen_ellipse_record;
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, color) == 0, "ScreenEllipse.color");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, filled) == 8, "ScreenEllipse.filled");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, cx) == 16, "ScreenEllipse.cx");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, cy) == 24, "ScreenEllipse.cy");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, rx) == 32, "ScreenEllipse.rx");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, ry) == 40, "ScreenEllipse.ry");
SHIP_ASSERT(sizeof(ship_screen_ellipse_record) == 48, "ScreenEllipse size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_ellipse_record) == 8, "ScreenEllipse alignment");
typedef struct {
    uint64_t id;
    uint64_t screen;
    uint64_t kind;
    uint64_t code;
    uint64_t modifiers;
    double x;
    double y;
    ship_text64 text;
} ship_screen_event_record;
SHIP_ASSERT(offsetof(ship_screen_event_record, id) == 0, "ScreenEvent.id");
SHIP_ASSERT(offsetof(ship_screen_event_record, screen) == 8, "ScreenEvent.screen");
SHIP_ASSERT(offsetof(ship_screen_event_record, kind) == 16, "ScreenEvent.kind");
SHIP_ASSERT(offsetof(ship_screen_event_record, code) == 24, "ScreenEvent.code");
SHIP_ASSERT(offsetof(ship_screen_event_record, modifiers) == 32, "ScreenEvent.modifiers");
SHIP_ASSERT(offsetof(ship_screen_event_record, x) == 40, "ScreenEvent.x");
SHIP_ASSERT(offsetof(ship_screen_event_record, y) == 48, "ScreenEvent.y");
SHIP_ASSERT(offsetof(ship_screen_event_record, text) == 56, "ScreenEvent.text");
SHIP_ASSERT(sizeof(ship_screen_event_record) == 128, "ScreenEvent size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_event_record) == 8, "ScreenEvent alignment");
typedef struct {
    uint64_t handle;
    uint64_t target_visible;
    double target_offset_m[3];
    double target_relative_velocity_m_s[3];
    double rotation[4];
    double angular_velocity_rad_s[3];
    double velocity_m_s[3];
    double maximum_acceleration_m_s2;
    double turn_rate_rad_s;
    uint64_t fuel_units;
    double dt_s;
    double time_s;
    double target_uncertainty_m;
} ship_missile_observation_record;
SHIP_ASSERT(offsetof(ship_missile_observation_record, handle) == 0, "MissileObservation.handle");
SHIP_ASSERT(offsetof(ship_missile_observation_record, target_visible) == 8, "MissileObservation.target_visible");
SHIP_ASSERT(offsetof(ship_missile_observation_record, target_offset_m) == 16, "MissileObservation.target_offset_m");
SHIP_ASSERT(offsetof(ship_missile_observation_record, target_relative_velocity_m_s) == 40, "MissileObservation.target_relative_velocity_m_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, rotation) == 64, "MissileObservation.rotation");
SHIP_ASSERT(offsetof(ship_missile_observation_record, angular_velocity_rad_s) == 96, "MissileObservation.angular_velocity_rad_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, velocity_m_s) == 120, "MissileObservation.velocity_m_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, maximum_acceleration_m_s2) == 144, "MissileObservation.maximum_acceleration_m_s2");
SHIP_ASSERT(offsetof(ship_missile_observation_record, turn_rate_rad_s) == 152, "MissileObservation.turn_rate_rad_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, fuel_units) == 160, "MissileObservation.fuel_units");
SHIP_ASSERT(offsetof(ship_missile_observation_record, dt_s) == 168, "MissileObservation.dt_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, time_s) == 176, "MissileObservation.time_s");
SHIP_ASSERT(offsetof(ship_missile_observation_record, target_uncertainty_m) == 184, "MissileObservation.target_uncertainty_m");
SHIP_ASSERT(sizeof(ship_missile_observation_record) == 192, "MissileObservation size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_missile_observation_record) == 8, "MissileObservation alignment");
typedef struct {
    double direction[3];
    double throttle;
} ship_missile_control_record;
SHIP_ASSERT(offsetof(ship_missile_control_record, direction) == 0, "MissileControl.direction");
SHIP_ASSERT(offsetof(ship_missile_control_record, throttle) == 24, "MissileControl.throttle");
SHIP_ASSERT(sizeof(ship_missile_control_record) == 32, "MissileControl size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_missile_control_record) == 8, "MissileControl alignment");
typedef struct {
    uint64_t propellant_resource;
    double per_axis_thrust_n;
    double per_axis_propellant_units_s;
    double per_axis_power_w;
} ship_rcs_spec_record;
SHIP_ASSERT(offsetof(ship_rcs_spec_record, propellant_resource) == 0, "RcsSpec.propellant_resource");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_thrust_n) == 8, "RcsSpec.per_axis_thrust_n");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_propellant_units_s) == 16, "RcsSpec.per_axis_propellant_units_s");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_power_w) == 24, "RcsSpec.per_axis_power_w");
SHIP_ASSERT(sizeof(ship_rcs_spec_record) == 32, "RcsSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_spec_record) == 8, "RcsSpec alignment");
typedef struct {
    double thrust_n[3];
} ship_rcs_setting_record;
SHIP_ASSERT(offsetof(ship_rcs_setting_record, thrust_n) == 0, "RcsSetting.thrust_n");
SHIP_ASSERT(sizeof(ship_rcs_setting_record) == 24, "RcsSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_setting_record) == 8, "RcsSetting alignment");
typedef struct {
    ship_device_status_record status;
    double thrust_n[3];
} ship_rcs_reading_record;
SHIP_ASSERT(offsetof(ship_rcs_reading_record, status) == 0, "RcsReading.status");
SHIP_ASSERT(offsetof(ship_rcs_reading_record, thrust_n) == 8, "RcsReading.thrust_n");
SHIP_ASSERT(sizeof(ship_rcs_reading_record) == 32, "RcsReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_reading_record) == 8, "RcsReading alignment");
typedef struct {
    uint32_t state;
    uint32_t bytes;
} ship_llm_poll_record;
SHIP_ASSERT(offsetof(ship_llm_poll_record, state) == 0, "LlmPoll.state");
SHIP_ASSERT(offsetof(ship_llm_poll_record, bytes) == 4, "LlmPoll.bytes");
SHIP_ASSERT(sizeof(ship_llm_poll_record) == 8, "LlmPoll size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_llm_poll_record) == 4, "LlmPoll alignment");
typedef struct {
    uint64_t next_sequence;
    uint64_t missed;
    uint32_t count;
    uint32_t reserved;
} ship_chat_page_record;
SHIP_ASSERT(offsetof(ship_chat_page_record, next_sequence) == 0, "ChatPage.next_sequence");
SHIP_ASSERT(offsetof(ship_chat_page_record, missed) == 8, "ChatPage.missed");
SHIP_ASSERT(offsetof(ship_chat_page_record, count) == 16, "ChatPage.count");
SHIP_ASSERT(offsetof(ship_chat_page_record, reserved) == 20, "ChatPage.reserved");
SHIP_ASSERT(sizeof(ship_chat_page_record) == 24, "ChatPage size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_chat_page_record) == 8, "ChatPage alignment");
typedef struct {
    uint8_t id[16];
    uint64_t sequence;
    uint64_t tick;
    int64_t calendar_unix_ms;
    uint8_t owner[16];
    uint8_t organization[16];
    uint32_t flags;
    uint32_t sender_bytes;
    uint32_t text_bytes;
    uint32_t reserved;
    uint8_t sender[128];
    uint8_t text[1024];
} ship_chat_message_record;
SHIP_ASSERT(offsetof(ship_chat_message_record, id) == 0, "ChatMessage.id");
SHIP_ASSERT(offsetof(ship_chat_message_record, sequence) == 16, "ChatMessage.sequence");
SHIP_ASSERT(offsetof(ship_chat_message_record, tick) == 24, "ChatMessage.tick");
SHIP_ASSERT(offsetof(ship_chat_message_record, calendar_unix_ms) == 32, "ChatMessage.calendar_unix_ms");
SHIP_ASSERT(offsetof(ship_chat_message_record, owner) == 40, "ChatMessage.owner");
SHIP_ASSERT(offsetof(ship_chat_message_record, organization) == 56, "ChatMessage.organization");
SHIP_ASSERT(offsetof(ship_chat_message_record, flags) == 72, "ChatMessage.flags");
SHIP_ASSERT(offsetof(ship_chat_message_record, sender_bytes) == 76, "ChatMessage.sender_bytes");
SHIP_ASSERT(offsetof(ship_chat_message_record, text_bytes) == 80, "ChatMessage.text_bytes");
SHIP_ASSERT(offsetof(ship_chat_message_record, reserved) == 84, "ChatMessage.reserved");
SHIP_ASSERT(offsetof(ship_chat_message_record, sender) == 88, "ChatMessage.sender");
SHIP_ASSERT(offsetof(ship_chat_message_record, text) == 216, "ChatMessage.text");
SHIP_ASSERT(sizeof(ship_chat_message_record) == 1240, "ChatMessage size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_chat_message_record) == 8, "ChatMessage alignment");
typedef struct {
    uint64_t words[6];
} ship_position_record;
SHIP_ASSERT(offsetof(ship_position_record, words) == 0, "Position.words");
SHIP_ASSERT(sizeof(ship_position_record) == 48, "Position size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_position_record) == 8, "Position alignment");
typedef struct {
    ship_position_record position;
    double velocity[3];
    double rotation[4];
    double angular_velocity[3];
} ship_pose_record;
SHIP_ASSERT(offsetof(ship_pose_record, position) == 0, "Pose.position");
SHIP_ASSERT(offsetof(ship_pose_record, velocity) == 48, "Pose.velocity");
SHIP_ASSERT(offsetof(ship_pose_record, rotation) == 72, "Pose.rotation");
SHIP_ASSERT(offsetof(ship_pose_record, angular_velocity) == 104, "Pose.angular_velocity");
SHIP_ASSERT(sizeof(ship_pose_record) == 128, "Pose size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_pose_record) == 8, "Pose alignment");
typedef struct {
    uint8_t group[16];
    uint8_t track[16];
} ship_contact_ref_record;
SHIP_ASSERT(offsetof(ship_contact_ref_record, group) == 0, "ContactRef.group");
SHIP_ASSERT(offsetof(ship_contact_ref_record, track) == 16, "ContactRef.track");
SHIP_ASSERT(sizeof(ship_contact_ref_record) == 32, "ContactRef size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_ref_record) == 1, "ContactRef alignment");
typedef struct {
    uint64_t kind;
    uint8_t entity[16];
    uint8_t system[16];
    ship_position_record position;
    uint64_t axes;
} ship_destination_record;
SHIP_ASSERT(offsetof(ship_destination_record, kind) == 0, "Destination.kind");
SHIP_ASSERT(offsetof(ship_destination_record, entity) == 8, "Destination.entity");
SHIP_ASSERT(offsetof(ship_destination_record, system) == 24, "Destination.system");
SHIP_ASSERT(offsetof(ship_destination_record, position) == 40, "Destination.position");
SHIP_ASSERT(offsetof(ship_destination_record, axes) == 88, "Destination.axes");
SHIP_ASSERT(sizeof(ship_destination_record) == 96, "Destination size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_destination_record) == 8, "Destination alignment");
typedef struct {
    uint64_t kind;
    double direction[3];
    ship_destination_record destination;
    ship_contact_ref_record contact;
} ship_target_record;
SHIP_ASSERT(offsetof(ship_target_record, kind) == 0, "Target.kind");
SHIP_ASSERT(offsetof(ship_target_record, direction) == 8, "Target.direction");
SHIP_ASSERT(offsetof(ship_target_record, destination) == 32, "Target.destination");
SHIP_ASSERT(offsetof(ship_target_record, contact) == 128, "Target.contact");
SHIP_ASSERT(sizeof(ship_target_record) == 160, "Target size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_target_record) == 8, "Target alignment");
typedef struct {
    uint64_t kind;
    uint8_t entity[16];
    ship_destination_record destination;
    ship_target_record target;
    uint64_t mode;
    double range_m;
    uint64_t tick;
    double speed_ly_s;
    uint64_t navigation_beacon_present;
    uint8_t navigation_beacon[16];
} ship_order_record;
SHIP_ASSERT(offsetof(ship_order_record, kind) == 0, "Order.kind");
SHIP_ASSERT(offsetof(ship_order_record, entity) == 8, "Order.entity");
SHIP_ASSERT(offsetof(ship_order_record, destination) == 24, "Order.destination");
SHIP_ASSERT(offsetof(ship_order_record, target) == 120, "Order.target");
SHIP_ASSERT(offsetof(ship_order_record, mode) == 280, "Order.mode");
SHIP_ASSERT(offsetof(ship_order_record, range_m) == 288, "Order.range_m");
SHIP_ASSERT(offsetof(ship_order_record, tick) == 296, "Order.tick");
SHIP_ASSERT(offsetof(ship_order_record, speed_ly_s) == 304, "Order.speed_ly_s");
SHIP_ASSERT(offsetof(ship_order_record, navigation_beacon_present) == 312, "Order.navigation_beacon_present");
SHIP_ASSERT(offsetof(ship_order_record, navigation_beacon) == 320, "Order.navigation_beacon");
SHIP_ASSERT(sizeof(ship_order_record) == 336, "Order size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_order_record) == 8, "Order alignment");
typedef struct {
    ship_text256 label;
    ship_order_record action;
    double seconds_per_kg;
    uint64_t duration_present;
    uint64_t duration_ticks;
    uint64_t propellant_present;
    double propellant_kg;
    uint64_t loss_present;
    double loss_ppm;
} ship_queued_order_record;
SHIP_ASSERT(offsetof(ship_queued_order_record, label) == 0, "QueuedOrder.label");
SHIP_ASSERT(offsetof(ship_queued_order_record, action) == 264, "QueuedOrder.action");
SHIP_ASSERT(offsetof(ship_queued_order_record, seconds_per_kg) == 600, "QueuedOrder.seconds_per_kg");
SHIP_ASSERT(offsetof(ship_queued_order_record, duration_present) == 608, "QueuedOrder.duration_present");
SHIP_ASSERT(offsetof(ship_queued_order_record, duration_ticks) == 616, "QueuedOrder.duration_ticks");
SHIP_ASSERT(offsetof(ship_queued_order_record, propellant_present) == 624, "QueuedOrder.propellant_present");
SHIP_ASSERT(offsetof(ship_queued_order_record, propellant_kg) == 632, "QueuedOrder.propellant_kg");
SHIP_ASSERT(offsetof(ship_queued_order_record, loss_present) == 640, "QueuedOrder.loss_present");
SHIP_ASSERT(offsetof(ship_queued_order_record, loss_ppm) == 648, "QueuedOrder.loss_ppm");
SHIP_ASSERT(sizeof(ship_queued_order_record) == 656, "QueuedOrder size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_queued_order_record) == 8, "QueuedOrder alignment");
typedef struct {
    double fuel_fraction;
    double max_loss_ppm;
    uint64_t allow_slipdrive;
} ship_preferences_record;
SHIP_ASSERT(offsetof(ship_preferences_record, fuel_fraction) == 0, "Preferences.fuel_fraction");
SHIP_ASSERT(offsetof(ship_preferences_record, max_loss_ppm) == 8, "Preferences.max_loss_ppm");
SHIP_ASSERT(offsetof(ship_preferences_record, allow_slipdrive) == 16, "Preferences.allow_slipdrive");
SHIP_ASSERT(sizeof(ship_preferences_record) == 24, "Preferences size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_preferences_record) == 8, "Preferences alignment");
typedef struct {
    ship_position_record reference;
} ship_orrery_query_record;
SHIP_ASSERT(offsetof(ship_orrery_query_record, reference) == 0, "OrreryQuery.reference");
SHIP_ASSERT(sizeof(ship_orrery_query_record) == 48, "OrreryQuery size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_orrery_query_record) == 8, "OrreryQuery alignment");
typedef struct {
    ship_target_record reference;
    ship_pose_record pose;
    double radius_m;
    double slip_exclusion_m;
} ship_local_obstacle_record;
SHIP_ASSERT(offsetof(ship_local_obstacle_record, reference) == 0, "LocalObstacle.reference");
SHIP_ASSERT(offsetof(ship_local_obstacle_record, pose) == 160, "LocalObstacle.pose");
SHIP_ASSERT(offsetof(ship_local_obstacle_record, radius_m) == 288, "LocalObstacle.radius_m");
SHIP_ASSERT(offsetof(ship_local_obstacle_record, slip_exclusion_m) == 296, "LocalObstacle.slip_exclusion_m");
SHIP_ASSERT(sizeof(ship_local_obstacle_record) == 304, "LocalObstacle size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_local_obstacle_record) == 8, "LocalObstacle alignment");
typedef struct {
    uint64_t count;
} ship_orrery_reply_record;
SHIP_ASSERT(offsetof(ship_orrery_reply_record, count) == 0, "OrreryReply.count");
SHIP_ASSERT(sizeof(ship_orrery_reply_record) == 8, "OrreryReply size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_orrery_reply_record) == 8, "OrreryReply alignment");
typedef struct {
    ship_pose_record pose;
    uint64_t handle;
    double radius_m;
} ship_contact_reply_record;
SHIP_ASSERT(offsetof(ship_contact_reply_record, pose) == 0, "ContactReply.pose");
SHIP_ASSERT(offsetof(ship_contact_reply_record, handle) == 128, "ContactReply.handle");
SHIP_ASSERT(offsetof(ship_contact_reply_record, radius_m) == 136, "ContactReply.radius_m");
SHIP_ASSERT(sizeof(ship_contact_reply_record) == 144, "ContactReply size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_reply_record) == 8, "ContactReply alignment");
typedef struct {
    ship_position_record origin;
    ship_position_record destination;
    double departure_after_seconds;
    double arrival_after_seconds;
    double speed_ly_s;
    uint64_t navigation_beacon_present;
    uint8_t navigation_beacon[16];
} ship_slip_eligibility_query_record;
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, origin) == 0, "SlipEligibilityQuery.origin");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, destination) == 48, "SlipEligibilityQuery.destination");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, departure_after_seconds) == 96, "SlipEligibilityQuery.departure_after_seconds");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, arrival_after_seconds) == 104, "SlipEligibilityQuery.arrival_after_seconds");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, speed_ly_s) == 112, "SlipEligibilityQuery.speed_ly_s");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, navigation_beacon_present) == 120, "SlipEligibilityQuery.navigation_beacon_present");
SHIP_ASSERT(offsetof(ship_slip_eligibility_query_record, navigation_beacon) == 128, "SlipEligibilityQuery.navigation_beacon");
SHIP_ASSERT(sizeof(ship_slip_eligibility_query_record) == 144, "SlipEligibilityQuery size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_slip_eligibility_query_record) == 8, "SlipEligibilityQuery alignment");
typedef struct {
    uint64_t ready;
    double preparation_s;
    double duration_s;
} ship_slip_eligibility_reply_record;
SHIP_ASSERT(offsetof(ship_slip_eligibility_reply_record, ready) == 0, "SlipEligibilityReply.ready");
SHIP_ASSERT(offsetof(ship_slip_eligibility_reply_record, preparation_s) == 8, "SlipEligibilityReply.preparation_s");
SHIP_ASSERT(offsetof(ship_slip_eligibility_reply_record, duration_s) == 16, "SlipEligibilityReply.duration_s");
SHIP_ASSERT(sizeof(ship_slip_eligibility_reply_record) == 24, "SlipEligibilityReply size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_slip_eligibility_reply_record) == 8, "SlipEligibilityReply alignment");
typedef struct {
    ship_destination_record destination;
    double after_seconds;
} ship_resolve_query_record;
SHIP_ASSERT(offsetof(ship_resolve_query_record, destination) == 0, "ResolveQuery.destination");
SHIP_ASSERT(offsetof(ship_resolve_query_record, after_seconds) == 96, "ResolveQuery.after_seconds");
SHIP_ASSERT(sizeof(ship_resolve_query_record) == 104, "ResolveQuery size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_resolve_query_record) == 8, "ResolveQuery alignment");
typedef struct {
    uint64_t autopilot_enabled;
    ship_preferences_record preferences;
    uint64_t revision;
    uint64_t index;
    uint64_t order_present;
    ship_queued_order_record order;
    uint64_t status;
    ship_text256 reason;
    uint64_t arrival_present;
    uint64_t arrival_tick;
    ship_pose_record pose;
    uint64_t slip_ready;
} ship_travel_reply_record;
SHIP_ASSERT(offsetof(ship_travel_reply_record, autopilot_enabled) == 0, "TravelReply.autopilot_enabled");
SHIP_ASSERT(offsetof(ship_travel_reply_record, preferences) == 8, "TravelReply.preferences");
SHIP_ASSERT(offsetof(ship_travel_reply_record, revision) == 32, "TravelReply.revision");
SHIP_ASSERT(offsetof(ship_travel_reply_record, index) == 40, "TravelReply.index");
SHIP_ASSERT(offsetof(ship_travel_reply_record, order_present) == 48, "TravelReply.order_present");
SHIP_ASSERT(offsetof(ship_travel_reply_record, order) == 56, "TravelReply.order");
SHIP_ASSERT(offsetof(ship_travel_reply_record, status) == 712, "TravelReply.status");
SHIP_ASSERT(offsetof(ship_travel_reply_record, reason) == 720, "TravelReply.reason");
SHIP_ASSERT(offsetof(ship_travel_reply_record, arrival_present) == 984, "TravelReply.arrival_present");
SHIP_ASSERT(offsetof(ship_travel_reply_record, arrival_tick) == 992, "TravelReply.arrival_tick");
SHIP_ASSERT(offsetof(ship_travel_reply_record, pose) == 1000, "TravelReply.pose");
SHIP_ASSERT(offsetof(ship_travel_reply_record, slip_ready) == 1128, "TravelReply.slip_ready");
SHIP_ASSERT(sizeof(ship_travel_reply_record) == 1136, "TravelReply size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_travel_reply_record) == 8, "TravelReply alignment");
typedef struct {
    uint64_t id;
    ship_preferences_record preferences;
} ship_route_request_record;
SHIP_ASSERT(offsetof(ship_route_request_record, id) == 0, "RouteRequest.id");
SHIP_ASSERT(offsetof(ship_route_request_record, preferences) == 8, "RouteRequest.preferences");
SHIP_ASSERT(sizeof(ship_route_request_record) == 32, "RouteRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_route_request_record) == 8, "RouteRequest alignment");
typedef struct {
    uint64_t id;
} ship_route_poll_record;
SHIP_ASSERT(offsetof(ship_route_poll_record, id) == 0, "RoutePoll.id");
SHIP_ASSERT(sizeof(ship_route_poll_record) == 8, "RoutePoll size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_route_poll_record) == 8, "RoutePoll alignment");
typedef struct {
    ship_text64 resource;
    double required_kg;
    double available_kg;
} ship_fuel_requirement_record;
SHIP_ASSERT(offsetof(ship_fuel_requirement_record, resource) == 0, "FuelRequirement.resource");
SHIP_ASSERT(offsetof(ship_fuel_requirement_record, required_kg) == 72, "FuelRequirement.required_kg");
SHIP_ASSERT(offsetof(ship_fuel_requirement_record, available_kg) == 80, "FuelRequirement.available_kg");
SHIP_ASSERT(sizeof(ship_fuel_requirement_record) == 88, "FuelRequirement size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_fuel_requirement_record) == 8, "FuelRequirement alignment");
typedef struct {
    uint64_t id;
    uint64_t status;
    uint64_t stage;
    uint64_t completed;
    uint64_t total_present;
    uint64_t total;
    uint64_t planned_tick;
    uint64_t travel_revision;
    uint64_t topology_revision;
    uint64_t order_count;
    uint64_t fuel_count;
    uint64_t fuel_complete;
    ship_text256 reason;
    double estimated_loss_ppm;
    double exotic_fuel_kg;
} ship_route_reply_record;
SHIP_ASSERT(offsetof(ship_route_reply_record, id) == 0, "RouteReply.id");
SHIP_ASSERT(offsetof(ship_route_reply_record, status) == 8, "RouteReply.status");
SHIP_ASSERT(offsetof(ship_route_reply_record, stage) == 16, "RouteReply.stage");
SHIP_ASSERT(offsetof(ship_route_reply_record, completed) == 24, "RouteReply.completed");
SHIP_ASSERT(offsetof(ship_route_reply_record, total_present) == 32, "RouteReply.total_present");
SHIP_ASSERT(offsetof(ship_route_reply_record, total) == 40, "RouteReply.total");
SHIP_ASSERT(offsetof(ship_route_reply_record, planned_tick) == 48, "RouteReply.planned_tick");
SHIP_ASSERT(offsetof(ship_route_reply_record, travel_revision) == 56, "RouteReply.travel_revision");
SHIP_ASSERT(offsetof(ship_route_reply_record, topology_revision) == 64, "RouteReply.topology_revision");
SHIP_ASSERT(offsetof(ship_route_reply_record, order_count) == 72, "RouteReply.order_count");
SHIP_ASSERT(offsetof(ship_route_reply_record, fuel_count) == 80, "RouteReply.fuel_count");
SHIP_ASSERT(offsetof(ship_route_reply_record, fuel_complete) == 88, "RouteReply.fuel_complete");
SHIP_ASSERT(offsetof(ship_route_reply_record, reason) == 96, "RouteReply.reason");
SHIP_ASSERT(offsetof(ship_route_reply_record, estimated_loss_ppm) == 360, "RouteReply.estimated_loss_ppm");
SHIP_ASSERT(offsetof(ship_route_reply_record, exotic_fuel_kg) == 368, "RouteReply.exotic_fuel_kg");
SHIP_ASSERT(sizeof(ship_route_reply_record) == 376, "RouteReply size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_route_reply_record) == 8, "RouteReply alignment");
typedef struct {
    uint64_t id;
    uint64_t revision;
    uint64_t engage;
} ship_use_route_record;
SHIP_ASSERT(offsetof(ship_use_route_record, id) == 0, "UseRoute.id");
SHIP_ASSERT(offsetof(ship_use_route_record, revision) == 8, "UseRoute.revision");
SHIP_ASSERT(offsetof(ship_use_route_record, engage) == 16, "UseRoute.engage");
SHIP_ASSERT(sizeof(ship_use_route_record) == 24, "UseRoute size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_use_route_record) == 8, "UseRoute alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
    ship_text256 reason;
} ship_block_record;
SHIP_ASSERT(offsetof(ship_block_record, revision) == 0, "Block.revision");
SHIP_ASSERT(offsetof(ship_block_record, order) == 8, "Block.order");
SHIP_ASSERT(offsetof(ship_block_record, reason) == 16, "Block.reason");
SHIP_ASSERT(sizeof(ship_block_record) == 280, "Block size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_block_record) == 8, "Block alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
    uint64_t ticks_present;
    uint64_t remaining_ticks;
    uint64_t propellant_present;
    double remaining_propellant_kg;
} ship_estimate_record;
SHIP_ASSERT(offsetof(ship_estimate_record, revision) == 0, "Estimate.revision");
SHIP_ASSERT(offsetof(ship_estimate_record, order) == 8, "Estimate.order");
SHIP_ASSERT(offsetof(ship_estimate_record, ticks_present) == 16, "Estimate.ticks_present");
SHIP_ASSERT(offsetof(ship_estimate_record, remaining_ticks) == 24, "Estimate.remaining_ticks");
SHIP_ASSERT(offsetof(ship_estimate_record, propellant_present) == 32, "Estimate.propellant_present");
SHIP_ASSERT(offsetof(ship_estimate_record, remaining_propellant_kg) == 40, "Estimate.remaining_propellant_kg");
SHIP_ASSERT(sizeof(ship_estimate_record) == 48, "Estimate size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_estimate_record) == 8, "Estimate alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
} ship_complete_order_record;
SHIP_ASSERT(offsetof(ship_complete_order_record, revision) == 0, "CompleteOrder.revision");
SHIP_ASSERT(offsetof(ship_complete_order_record, order) == 8, "CompleteOrder.order");
SHIP_ASSERT(sizeof(ship_complete_order_record) == 16, "CompleteOrder size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_complete_order_record) == 8, "CompleteOrder alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
    ship_position_record destination;
    double speed_ly_s;
    uint64_t navigation_beacon_present;
    uint8_t navigation_beacon[16];
} ship_slip_record;
SHIP_ASSERT(offsetof(ship_slip_record, revision) == 0, "Slip.revision");
SHIP_ASSERT(offsetof(ship_slip_record, order) == 8, "Slip.order");
SHIP_ASSERT(offsetof(ship_slip_record, destination) == 16, "Slip.destination");
SHIP_ASSERT(offsetof(ship_slip_record, speed_ly_s) == 64, "Slip.speed_ly_s");
SHIP_ASSERT(offsetof(ship_slip_record, navigation_beacon_present) == 72, "Slip.navigation_beacon_present");
SHIP_ASSERT(offsetof(ship_slip_record, navigation_beacon) == 80, "Slip.navigation_beacon");
SHIP_ASSERT(sizeof(ship_slip_record) == 96, "Slip size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_slip_record) == 8, "Slip alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
    uint8_t station[16];
    uint64_t bay;
} ship_reserve_bay_record;
SHIP_ASSERT(offsetof(ship_reserve_bay_record, revision) == 0, "ReserveBay.revision");
SHIP_ASSERT(offsetof(ship_reserve_bay_record, order) == 8, "ReserveBay.order");
SHIP_ASSERT(offsetof(ship_reserve_bay_record, station) == 16, "ReserveBay.station");
SHIP_ASSERT(offsetof(ship_reserve_bay_record, bay) == 32, "ReserveBay.bay");
SHIP_ASSERT(sizeof(ship_reserve_bay_record) == 40, "ReserveBay size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_reserve_bay_record) == 8, "ReserveBay alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
    uint8_t station[16];
    uint64_t bay;
} ship_dock_record;
SHIP_ASSERT(offsetof(ship_dock_record, revision) == 0, "Dock.revision");
SHIP_ASSERT(offsetof(ship_dock_record, order) == 8, "Dock.order");
SHIP_ASSERT(offsetof(ship_dock_record, station) == 16, "Dock.station");
SHIP_ASSERT(offsetof(ship_dock_record, bay) == 32, "Dock.bay");
SHIP_ASSERT(sizeof(ship_dock_record) == 40, "Dock size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_dock_record) == 8, "Dock alignment");
typedef struct {
    uint64_t revision;
    uint64_t order;
} ship_undock_record;
SHIP_ASSERT(offsetof(ship_undock_record, revision) == 0, "Undock.revision");
SHIP_ASSERT(offsetof(ship_undock_record, order) == 8, "Undock.order");
SHIP_ASSERT(sizeof(ship_undock_record) == 16, "Undock size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_undock_record) == 8, "Undock alignment");
typedef struct {
    uint64_t kind;
    uint8_t id[16];
    ship_text64 text;
} ship_tag_record;
SHIP_ASSERT(offsetof(ship_tag_record, kind) == 0, "Tag.kind");
SHIP_ASSERT(offsetof(ship_tag_record, id) == 8, "Tag.id");
SHIP_ASSERT(offsetof(ship_tag_record, text) == 24, "Tag.text");
SHIP_ASSERT(sizeof(ship_tag_record) == 96, "Tag size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_tag_record) == 8, "Tag alignment");
typedef struct {
    uint64_t flags;
    uint8_t track[16];
    ship_position_record centre;
    double radius_m;
    uint64_t max_age_ticks;
    uint64_t work;
    uint32_t limit;
    uint32_t all_count;
    uint32_t any_count;
    uint32_t exclude_count;
} ship_track_query_record;
SHIP_ASSERT(offsetof(ship_track_query_record, flags) == 0, "TrackQuery.flags");
SHIP_ASSERT(offsetof(ship_track_query_record, track) == 8, "TrackQuery.track");
SHIP_ASSERT(offsetof(ship_track_query_record, centre) == 24, "TrackQuery.centre");
SHIP_ASSERT(offsetof(ship_track_query_record, radius_m) == 72, "TrackQuery.radius_m");
SHIP_ASSERT(offsetof(ship_track_query_record, max_age_ticks) == 80, "TrackQuery.max_age_ticks");
SHIP_ASSERT(offsetof(ship_track_query_record, work) == 88, "TrackQuery.work");
SHIP_ASSERT(offsetof(ship_track_query_record, limit) == 96, "TrackQuery.limit");
SHIP_ASSERT(offsetof(ship_track_query_record, all_count) == 100, "TrackQuery.all_count");
SHIP_ASSERT(offsetof(ship_track_query_record, any_count) == 104, "TrackQuery.any_count");
SHIP_ASSERT(offsetof(ship_track_query_record, exclude_count) == 108, "TrackQuery.exclude_count");
SHIP_ASSERT(sizeof(ship_track_query_record) == 112, "TrackQuery size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_track_query_record) == 8, "TrackQuery alignment");
typedef struct {
    uint8_t spatial_instance[16];
    uint8_t id[16];
    uint8_t entity[16];
    ship_pose_record pose;
    double position_sigma_m;
    double velocity_sigma_m_s;
    uint64_t observed_tick;
    uint64_t estimate_tick;
    double radius_m;
    uint8_t appearance[32];
    uint32_t flags;
    uint32_t provenance;
    uint32_t tags_offset;
    uint32_t tags_count;
} ship_track_record;
SHIP_ASSERT(offsetof(ship_track_record, spatial_instance) == 0, "Track.spatial_instance");
SHIP_ASSERT(offsetof(ship_track_record, id) == 16, "Track.id");
SHIP_ASSERT(offsetof(ship_track_record, entity) == 32, "Track.entity");
SHIP_ASSERT(offsetof(ship_track_record, pose) == 48, "Track.pose");
SHIP_ASSERT(offsetof(ship_track_record, position_sigma_m) == 176, "Track.position_sigma_m");
SHIP_ASSERT(offsetof(ship_track_record, velocity_sigma_m_s) == 184, "Track.velocity_sigma_m_s");
SHIP_ASSERT(offsetof(ship_track_record, observed_tick) == 192, "Track.observed_tick");
SHIP_ASSERT(offsetof(ship_track_record, estimate_tick) == 200, "Track.estimate_tick");
SHIP_ASSERT(offsetof(ship_track_record, radius_m) == 208, "Track.radius_m");
SHIP_ASSERT(offsetof(ship_track_record, appearance) == 216, "Track.appearance");
SHIP_ASSERT(offsetof(ship_track_record, flags) == 248, "Track.flags");
SHIP_ASSERT(offsetof(ship_track_record, provenance) == 252, "Track.provenance");
SHIP_ASSERT(offsetof(ship_track_record, tags_offset) == 256, "Track.tags_offset");
SHIP_ASSERT(offsetof(ship_track_record, tags_count) == 260, "Track.tags_count");
SHIP_ASSERT(sizeof(ship_track_record) == 264, "Track size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_track_record) == 8, "Track alignment");
typedef struct {
    uint64_t revision;
    uint64_t gas_used;
    uint8_t continuation[16];
    uint32_t count;
    uint32_t completion;
    uint32_t has_continuation;
    uint32_t arena_bytes;
} ship_track_page_record;
SHIP_ASSERT(offsetof(ship_track_page_record, revision) == 0, "TrackPage.revision");
SHIP_ASSERT(offsetof(ship_track_page_record, gas_used) == 8, "TrackPage.gas_used");
SHIP_ASSERT(offsetof(ship_track_page_record, continuation) == 16, "TrackPage.continuation");
SHIP_ASSERT(offsetof(ship_track_page_record, count) == 32, "TrackPage.count");
SHIP_ASSERT(offsetof(ship_track_page_record, completion) == 36, "TrackPage.completion");
SHIP_ASSERT(offsetof(ship_track_page_record, has_continuation) == 40, "TrackPage.has_continuation");
SHIP_ASSERT(offsetof(ship_track_page_record, arena_bytes) == 44, "TrackPage.arena_bytes");
SHIP_ASSERT(sizeof(ship_track_page_record) == 48, "TrackPage size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_track_page_record) == 8, "TrackPage alignment");
typedef struct {
    uint64_t index;
    ship_pose_record pose;
} ship_bay_record;
SHIP_ASSERT(offsetof(ship_bay_record, index) == 0, "Bay.index");
SHIP_ASSERT(offsetof(ship_bay_record, pose) == 8, "Bay.pose");
SHIP_ASSERT(sizeof(ship_bay_record) == 136, "Bay size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_bay_record) == 8, "Bay alignment");
typedef struct {
    uint8_t entity[16];
    ship_pose_record pose;
    double radius_m;
    uint8_t owner[16];
    uint8_t faction[16];
    double range_m;
    uint32_t flags;
    uint32_t labels_offset;
    uint32_t labels_count;
    uint32_t bays_offset;
    uint32_t bays_count;
    uint32_t reserved;
} ship_beacon_record;
SHIP_ASSERT(offsetof(ship_beacon_record, entity) == 0, "Beacon.entity");
SHIP_ASSERT(offsetof(ship_beacon_record, pose) == 16, "Beacon.pose");
SHIP_ASSERT(offsetof(ship_beacon_record, radius_m) == 144, "Beacon.radius_m");
SHIP_ASSERT(offsetof(ship_beacon_record, owner) == 152, "Beacon.owner");
SHIP_ASSERT(offsetof(ship_beacon_record, faction) == 168, "Beacon.faction");
SHIP_ASSERT(offsetof(ship_beacon_record, range_m) == 184, "Beacon.range_m");
SHIP_ASSERT(offsetof(ship_beacon_record, flags) == 192, "Beacon.flags");
SHIP_ASSERT(offsetof(ship_beacon_record, labels_offset) == 196, "Beacon.labels_offset");
SHIP_ASSERT(offsetof(ship_beacon_record, labels_count) == 200, "Beacon.labels_count");
SHIP_ASSERT(offsetof(ship_beacon_record, bays_offset) == 204, "Beacon.bays_offset");
SHIP_ASSERT(offsetof(ship_beacon_record, bays_count) == 208, "Beacon.bays_count");
SHIP_ASSERT(offsetof(ship_beacon_record, reserved) == 212, "Beacon.reserved");
SHIP_ASSERT(sizeof(ship_beacon_record) == 216, "Beacon size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_beacon_record) == 8, "Beacon alignment");
typedef struct {
    uint32_t count;
    uint32_t arena_bytes;
} ship_beacon_page_record;
SHIP_ASSERT(offsetof(ship_beacon_page_record, count) == 0, "BeaconPage.count");
SHIP_ASSERT(offsetof(ship_beacon_page_record, arena_bytes) == 4, "BeaconPage.arena_bytes");
SHIP_ASSERT(sizeof(ship_beacon_page_record) == 8, "BeaconPage size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_beacon_page_record) == 4, "BeaconPage alignment");
SHIP_IMPORT("llm_submit") int32_t ship_llm_submit(uint64_t id, const void * input, uint32_t bytes, uint32_t max_tokens);
SHIP_IMPORT("llm_poll") int32_t ship_llm_poll(uint64_t id, void * out, uint32_t capacity, ship_llm_poll_record * status);
SHIP_IMPORT("llm_cancel") int32_t ship_llm_cancel(uint64_t id);
SHIP_IMPORT("serial_write") int32_t ship_serial_write(const void * input, uint32_t bytes);
SHIP_IMPORT("chat_send") int32_t ship_chat_send(uint64_t id, const void * input, uint32_t bytes);
SHIP_IMPORT("chat_read") int32_t ship_chat_read(uint64_t after, ship_chat_message_record * out, uint32_t capacity, ship_chat_page_record * page);
SHIP_IMPORT("missile_read") int32_t ship_missile_read(void * output, uint32_t bytes);
SHIP_IMPORT("missile_control") int32_t ship_missile_control(const void * input, uint32_t bytes);
SHIP_IMPORT("persistent_read") int32_t ship_persistent_read(void * output, uint32_t capacity);
SHIP_IMPORT("persistent_write") int32_t ship_persistent_write(const void * input, uint32_t length);
SHIP_IMPORT("tick_read") int32_t ship_tick_read(void * out, uint32_t bytes);
SHIP_IMPORT("budget_read") int32_t ship_budget_read(void * out, uint32_t bytes);
SHIP_IMPORT("flight_read") int32_t ship_flight_read(void * out, uint32_t bytes);
SHIP_IMPORT("ship_resources_read") int32_t ship_ship_resources_read(void * out, uint32_t bytes);
SHIP_IMPORT("tick_set_interval") int32_t ship_tick_set_interval(double seconds);
SHIP_IMPORT("snapshot_keep") int32_t ship_snapshot_keep(uint64_t snapshot);
SHIP_IMPORT("snapshot_drop") int32_t ship_snapshot_drop(uint64_t snapshot);
SHIP_IMPORT("device_info") int32_t ship_device_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("device_group_read") int32_t ship_device_group_read(uint64_t device, uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("device_spec") int32_t ship_device_spec(uint64_t device, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("device_read") int32_t ship_device_read(uint64_t device, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("device_write") int32_t ship_device_write(uint64_t device, uint64_t setting, const void * input, uint32_t bytes);
SHIP_IMPORT("resource_info") int32_t ship_resource_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("resource_read") int32_t ship_resource_read(uint64_t resource, void * out, uint32_t bytes);
SHIP_IMPORT("sensor_scan") int32_t ship_sensor_scan(uint64_t sensor, uint32_t maximum, void * contacts, uint32_t contacts_bytes);
SHIP_IMPORT("contact_label") int32_t ship_contact_label(uint64_t contact, void * out, uint32_t bytes);
SHIP_IMPORT("request_info") int32_t ship_request_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("request_read") int32_t ship_request_read(uint32_t index, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("request_reply") int32_t ship_request_reply(uint64_t request, uint64_t result, const void * message, uint32_t message_bytes);
SHIP_IMPORT("instrument_weapons_put") int32_t ship_instrument_weapons_put(const void * state_pointer, uint32_t state_bytes, const void * weapons_pointer, uint32_t weapon_count);
SHIP_IMPORT("instrument_attitude_put") int32_t ship_instrument_attitude_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_navigation_put") int32_t ship_instrument_navigation_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_contacts_put") int32_t ship_instrument_contacts_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_clear") int32_t ship_instrument_clear(uint64_t kind);
SHIP_IMPORT("spatial_marker_put") int32_t ship_spatial_marker_put(const void * marker, uint32_t marker_bytes);
SHIP_IMPORT("spatial_path_put") int32_t ship_spatial_path_put(const void * path, uint32_t path_bytes, const void * vertices, uint32_t vertex_count);
SHIP_IMPORT("spatial_remove") int32_t ship_spatial_remove(uint64_t id);
SHIP_IMPORT("spatial_clear") int32_t ship_spatial_clear(void);
SHIP_IMPORT("screen_define") int32_t ship_screen_define(const void * input, uint32_t bytes);
SHIP_IMPORT("screen_remove") int32_t ship_screen_remove(uint64_t screen);
SHIP_IMPORT("screen_begin") int32_t ship_screen_begin(const void * input, uint32_t bytes);
SHIP_IMPORT("screen_draw") int32_t ship_screen_draw(uint64_t screen, uint64_t kind, const void * parameters, uint32_t parameter_bytes, const void * payload, uint32_t payload_bytes);
SHIP_IMPORT("screen_button") int32_t ship_screen_button(uint64_t screen, uint64_t key, const void * label, uint32_t label_bytes);
SHIP_IMPORT("screen_end") int32_t ship_screen_end(uint64_t screen);
SHIP_IMPORT("screen_event_read") int32_t ship_screen_event_read(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("screen_event_ack") int32_t ship_screen_event_ack(uint64_t event);
SHIP_IMPORT("orrery_read") int32_t ship_orrery_read(const ship_orrery_query_record * query, ship_local_obstacle_record * output, uint32_t capacity, ship_orrery_reply_record * reply);
SHIP_IMPORT("contact_get") int32_t ship_contact_get(const ship_contact_ref_record * query, ship_contact_reply_record * reply);
SHIP_IMPORT("slip_eligibility") int32_t ship_slip_eligibility(const ship_slip_eligibility_query_record * query, ship_slip_eligibility_reply_record * reply);
SHIP_IMPORT("travel_read") int32_t ship_travel_read(ship_travel_reply_record * reply);
SHIP_IMPORT("destination_resolve") int32_t ship_destination_resolve(const ship_resolve_query_record * query, ship_pose_record * reply);
SHIP_IMPORT("route_request") int32_t ship_route_request(const ship_route_request_record * query, const ship_order_record * orders, uint32_t count, ship_route_reply_record * reply, ship_queued_order_record * output, uint32_t capacity, ship_fuel_requirement_record * fuels, uint32_t fuel_capacity);
SHIP_IMPORT("route_poll") int32_t ship_route_poll(uint64_t id, ship_route_reply_record * reply, ship_queued_order_record * output, uint32_t capacity, ship_fuel_requirement_record * fuels, uint32_t fuel_capacity);
SHIP_IMPORT("travel_use_route") int32_t ship_travel_use_route(const ship_use_route_record * action);
SHIP_IMPORT("travel_block") int32_t ship_travel_block(const ship_block_record * action);
SHIP_IMPORT("travel_estimate") int32_t ship_travel_estimate(const ship_estimate_record * action);
SHIP_IMPORT("travel_complete") int32_t ship_travel_complete(const ship_complete_order_record * action);
SHIP_IMPORT("travel_slip") int32_t ship_travel_slip(const ship_slip_record * action);
SHIP_IMPORT("travel_reserve_bay") int32_t ship_travel_reserve_bay(const ship_reserve_bay_record * action);
SHIP_IMPORT("travel_dock") int32_t ship_travel_dock(const ship_dock_record * action);
SHIP_IMPORT("travel_undock") int32_t ship_travel_undock(const ship_undock_record * action);
SHIP_IMPORT("intel_tracks") int32_t ship_intel_tracks(const ship_track_query_record * query, const ship_tag_record * tags, ship_track_record * output, uint32_t capacity, void * arena, uint32_t arena_capacity, ship_track_page_record * page);
SHIP_IMPORT("intel_continue") int32_t ship_intel_continue(const void * cursor, uint64_t work, ship_track_record * output, uint32_t capacity, void * arena, uint32_t arena_capacity, ship_track_page_record * page);
SHIP_IMPORT("beacons_read") int32_t ship_beacons_read(const void * after, uint32_t has_after, ship_beacon_record * output, uint32_t capacity, void * arena, uint32_t arena_capacity, ship_beacon_page_record * page);
SHIP_IMPORT("beacon_read") int32_t ship_beacon_read(const void * id, ship_beacon_record * output, void * arena, uint32_t arena_capacity, ship_beacon_page_record * page);
/* Guest exports: uint32_t ship_api_version(void); void ship_tick(void); memory. */
#ifdef __cplusplus
}
#endif
#endif
