/* Generated by tools/generate_ship_bindings.py. wasm32, little endian. */
#ifndef TOY_SHIP_H
#define TOY_SHIP_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
#define SHIP_ASSERT static_assert
#define SHIP_ALIGNOF alignof
extern "C" {
#else
#define SHIP_ASSERT _Static_assert
#define SHIP_ALIGNOF _Alignof
#endif
#if defined(__wasm__)
#define SHIP_IMPORT(name) __attribute__((import_module("ship_v27"), import_name(name)))
#else
#define SHIP_IMPORT(name)
#endif
#define SHIP_API_VERSION (27)
#define SHIP_ERR_BUFFER (-2)
#define SHIP_ERR_ARGUMENT (-3)
#define SHIP_ERR_UNAVAILABLE (-4)
#define SHIP_ERR_LIMIT (-5)
#define SHIP_ERR_HANDLE (-6)
#define SHIP_ERR_UNSUPPORTED (-7)
#define SHIP_CALL_GAS (100)
#define SHIP_SCAN_GAS_PER_OBJECT (3000)
#define SHIP_NAVIGATION_GAS_BASE (100)
#define SHIP_NAVIGATION_GAS_PER_GATE (4096)
#define SHIP_MAX_CONTACTS (256)
#define SHIP_MAX_TRACKS (512)
#define SHIP_MAX_SNAPSHOTS (8)
#define SHIP_MAX_MARKERS (64)
#define SHIP_MAX_PATHS (8)
#define SHIP_MAX_PATH_VERTICES (128)
#define SHIP_MAX_TOTAL_VERTICES (1024)
#define SHIP_MAX_SCREENS (8)
#define SHIP_MAX_SCREEN_PRIMITIVES (256)
#define SHIP_MAX_SCREEN_PAYLOAD (65536)
#define SHIP_MAX_INPUTS (256)
#define SHIP_INTEREST_MARKERS (1)
#define SHIP_INTEREST_PATHS (2)
#define SHIP_FIRST_CALLBACK (1)
#define SHIP_OPERATIONAL (1)
#define SHIP_POWERED (2)
#define SHIP_CONTROL_ENABLED (1)
#define SHIP_CONTACT_SHIP (0)
#define SHIP_CONTACT_CELESTIAL (1)
#define SHIP_CONTACT_OTHER (2)
#define SHIP_DEVICE_ACCELEROMETER (0)
#define SHIP_DEVICE_COMPUTER (1)
#define SHIP_DEVICE_STORAGE (2)
#define SHIP_DEVICE_BATTERY (3)
#define SHIP_DEVICE_ENGINE (4)
#define SHIP_DEVICE_TORQUER (5)
#define SHIP_DEVICE_GENERATOR (6)
#define SHIP_DEVICE_SHIELD (7)
#define SHIP_DEVICE_SENSOR (8)
#define SHIP_SET_THROTTLE (0)
#define SHIP_SET_TORQUE (1)
#define SHIP_SET_GENERATOR_DEMAND (2)
#define SHIP_SET_SHIELD_ENABLED (3)
#define SHIP_SET_SENSOR_ENABLED (4)
#define SHIP_REQUEST_THROTTLE (11)
#define SHIP_REQUEST_MANUAL (0)
#define SHIP_REQUEST_HOLD_ATTITUDE (1)
#define SHIP_REQUEST_STOP_GUIDANCE (2)
#define SHIP_REQUEST_AIM_DIRECTION (3)
#define SHIP_REQUEST_AIM_CONTACT (4)
#define SHIP_REQUEST_SELECT_TARGET (5)
#define SHIP_REQUEST_ENGAGE_NAVIGATION (6)
#define SHIP_REPLY_ACCEPTED (0)
#define SHIP_REPLY_REJECTED (1)
#define SHIP_REPLY_UNSUPPORTED (2)
#define SHIP_FRAME_SNAPSHOT (0)
#define SHIP_FRAME_SHIP (1)
#define SHIP_FRAME_SHIP_BODY (2)
#define SHIP_FRAME_CONTACT (3)
#define SHIP_FRAME_PATH (4)
#define SHIP_TIME_CURRENT (0)
#define SHIP_TIME_FIXED (1)
#define SHIP_PATH_POLYLINE (0)
#define SHIP_PATH_TIMED (1)
#define SHIP_MARKER_ANNOTATION (0)
#define SHIP_MARKER_TARGET (1)
#define SHIP_MARKER_WAYPOINT (2)
#define SHIP_MARKER_AIM (3)
#define SHIP_MARKER_EVENT (4)
#define SHIP_PATH_REFERENCE (0)
#define SHIP_PATH_OWN_FORECAST (1)
#define SHIP_PATH_CONTACT_FORECAST (2)
#define SHIP_PATH_ROUTE (3)
#define SHIP_ATTITUDE_MANUAL (0)
#define SHIP_ATTITUDE_HOLD (1)
#define SHIP_ATTITUDE_GUIDANCE (2)
#define SHIP_ATTITUDE_REFERENCE (1)
#define SHIP_NAV_IDLE (0)
#define SHIP_NAV_ACTIVE (1)
#define SHIP_NAV_SUSPENDED (2)
#define SHIP_NAV_UNAVAILABLE (3)
#define SHIP_NAV_STAND_OFF (1)
#define SHIP_NAV_SPEED_LIMIT (2)
#define SHIP_NAV_BRAKING_DISTANCE (4)
#define SHIP_NAV_ARRIVAL (8)
#define SHIP_NAV_FUEL (16)
#define SHIP_INSTRUMENT_ATTITUDE (0)
#define SHIP_INSTRUMENT_NAVIGATION (1)
#define SHIP_INSTRUMENT_CONTACTS (2)
#define SHIP_DRAW_PIXEL (0)
#define SHIP_DRAW_TEXT (1)
#define SHIP_DRAW_LINE (2)
#define SHIP_DRAW_POLYLINE (3)
#define SHIP_DRAW_RECTANGLE (4)
#define SHIP_DRAW_ELLIPSE (5)
#define SHIP_EVENT_POINTER_MOVE (0)
#define SHIP_EVENT_POINTER_PRESS (1)
#define SHIP_EVENT_POINTER_RELEASE (2)
#define SHIP_EVENT_KEY_PRESS (3)
#define SHIP_EVENT_TEXT (4)
#define SHIP_EVENT_KEY_RELEASE (5)
#define SHIP_EVENT_BEZEL (6)
#define SHIP_EVENT_RESET (7)
#define SHIP_DEVICE_WEAPON (9)
#define SHIP_DEVICE_RCS (10)
#define SHIP_SET_RCS (6)
#define SHIP_WEAPON_PROPELLANT (4096)
#define SHIP_SET_WEAPON (5)
#define SHIP_REQUEST_MARK_TARGET (7)
#define SHIP_REQUEST_STOP_FIRING (8)
#define SHIP_REQUEST_UNMARK_TARGET (9)
#define SHIP_REQUEST_START_FIRING (10)
#define SHIP_INSTRUMENT_WEAPONS (3)
#define SHIP_CONTACT_PROJECTILE (3)
#define SHIP_WEAPONS_HOLD (0)
#define SHIP_WEAPONS_FIRING (1)
#define SHIP_WEAPON_UNAVAILABLE (1)
#define SHIP_WEAPON_AMMO (4)
#define SHIP_WEAPON_COOLDOWN (16)
#define SHIP_WEAPON_BLOCKED (128)
#define SHIP_WEAPON_TRAVEL (256)
#define SHIP_WEAPON_POINTING (512)
#define SHIP_WEAPON_EXPIRED (1024)
#define SHIP_WEAPON_ENERGY (2048)
#define SHIP_WEAPON_SOLUTION (1)
#define SHIP_WEAPON_ROW_GAS (100)
#define SHIP_SHIELD_ABSENT (0)
#define SHIP_SHIELD_OFF (1)
#define SHIP_SHIELD_ACTIVE (2)
#define SHIP_SHIELD_DEPLETED (3)
#define SHIP_SHIELD_UNPOWERED (4)
#define SHIP_SHIELD_BLOCKED (5)
typedef struct { uint64_t len; uint8_t bytes[64]; } ship_text64;
SHIP_ASSERT(sizeof(ship_text64) == 72, "text layout");
SHIP_ASSERT(SHIP_ALIGNOF(ship_text64) == 8, "text alignment");
typedef struct { uint64_t len; uint8_t bytes[256]; } ship_text256;
SHIP_ASSERT(sizeof(ship_text256) == 264, "text layout");
SHIP_ASSERT(SHIP_ALIGNOF(ship_text256) == 8, "text alignment");
typedef struct {
    double throttle;
} ship_throttle_request_record;
SHIP_ASSERT(offsetof(ship_throttle_request_record, throttle) == 0, "ThrottleRequest.throttle");
SHIP_ASSERT(sizeof(ship_throttle_request_record) == 8, "ThrottleRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_throttle_request_record) == 8, "ThrottleRequest alignment");
typedef struct {
    uint64_t tick;
    uint64_t snapshot;
    double time_s;
    double dt_s;
    double physics_dt_s;
    uint64_t device_count;
    uint64_t resource_count;
    uint64_t request_count;
    uint64_t screen_event_count;
    uint64_t interest;
    uint64_t requested_screens;
    uint64_t flags;
} ship_tick_context_record;
SHIP_ASSERT(offsetof(ship_tick_context_record, tick) == 0, "TickContext.tick");
SHIP_ASSERT(offsetof(ship_tick_context_record, snapshot) == 8, "TickContext.snapshot");
SHIP_ASSERT(offsetof(ship_tick_context_record, time_s) == 16, "TickContext.time_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, dt_s) == 24, "TickContext.dt_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, physics_dt_s) == 32, "TickContext.physics_dt_s");
SHIP_ASSERT(offsetof(ship_tick_context_record, device_count) == 40, "TickContext.device_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, resource_count) == 48, "TickContext.resource_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, request_count) == 56, "TickContext.request_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, screen_event_count) == 64, "TickContext.screen_event_count");
SHIP_ASSERT(offsetof(ship_tick_context_record, interest) == 72, "TickContext.interest");
SHIP_ASSERT(offsetof(ship_tick_context_record, requested_screens) == 80, "TickContext.requested_screens");
SHIP_ASSERT(offsetof(ship_tick_context_record, flags) == 88, "TickContext.flags");
SHIP_ASSERT(sizeof(ship_tick_context_record) == 96, "TickContext size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_tick_context_record) == 8, "TickContext alignment");
typedef struct {
    uint64_t gas_remaining;
    uint64_t gas_limit;
    uint64_t gas_per_tick;
} ship_budget_info_record;
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_remaining) == 0, "BudgetInfo.gas_remaining");
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_limit) == 8, "BudgetInfo.gas_limit");
SHIP_ASSERT(offsetof(ship_budget_info_record, gas_per_tick) == 16, "BudgetInfo.gas_per_tick");
SHIP_ASSERT(sizeof(ship_budget_info_record) == 24, "BudgetInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_budget_info_record) == 8, "BudgetInfo alignment");
typedef struct {
    double rotation[4];
    double angular_velocity[3];
    double velocity[3];
    double mass_kg;
    double inertia[9];
    double radius_m;
} ship_flight_state_record;
SHIP_ASSERT(offsetof(ship_flight_state_record, rotation) == 0, "FlightState.rotation");
SHIP_ASSERT(offsetof(ship_flight_state_record, angular_velocity) == 32, "FlightState.angular_velocity");
SHIP_ASSERT(offsetof(ship_flight_state_record, velocity) == 56, "FlightState.velocity");
SHIP_ASSERT(offsetof(ship_flight_state_record, mass_kg) == 80, "FlightState.mass_kg");
SHIP_ASSERT(offsetof(ship_flight_state_record, inertia) == 88, "FlightState.inertia");
SHIP_ASSERT(offsetof(ship_flight_state_record, radius_m) == 160, "FlightState.radius_m");
SHIP_ASSERT(sizeof(ship_flight_state_record) == 168, "FlightState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_flight_state_record) == 8, "FlightState alignment");
typedef struct {
    double hull_hp;
    double hull_max_hp;
    double hull_heat_j;
    double hull_heat_capacity_j;
    double shield_temperature_k;
    double shield_reserve_kg;
    double shield_reserve_capacity_kg;
    double shield_strength;
    uint64_t energy_j;
    uint64_t shield_state;
} ship_ship_resources_record;
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_hp) == 0, "ShipResources.hull_hp");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_max_hp) == 8, "ShipResources.hull_max_hp");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_heat_j) == 16, "ShipResources.hull_heat_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, hull_heat_capacity_j) == 24, "ShipResources.hull_heat_capacity_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_temperature_k) == 32, "ShipResources.shield_temperature_k");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_reserve_kg) == 40, "ShipResources.shield_reserve_kg");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_reserve_capacity_kg) == 48, "ShipResources.shield_reserve_capacity_kg");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_strength) == 56, "ShipResources.shield_strength");
SHIP_ASSERT(offsetof(ship_ship_resources_record, energy_j) == 64, "ShipResources.energy_j");
SHIP_ASSERT(offsetof(ship_ship_resources_record, shield_state) == 72, "ShipResources.shield_state");
SHIP_ASSERT(sizeof(ship_ship_resources_record) == 80, "ShipResources size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_ship_resources_record) == 8, "ShipResources alignment");
typedef struct {
    uint64_t id;
    uint64_t part_id;
    uint64_t kind;
    uint64_t flags;
    double position_m[3];
    double rotation[4];
    ship_text64 alias;
    uint64_t group_count;
} ship_device_info_record;
SHIP_ASSERT(offsetof(ship_device_info_record, id) == 0, "DeviceInfo.id");
SHIP_ASSERT(offsetof(ship_device_info_record, part_id) == 8, "DeviceInfo.part_id");
SHIP_ASSERT(offsetof(ship_device_info_record, kind) == 16, "DeviceInfo.kind");
SHIP_ASSERT(offsetof(ship_device_info_record, flags) == 24, "DeviceInfo.flags");
SHIP_ASSERT(offsetof(ship_device_info_record, position_m) == 32, "DeviceInfo.position_m");
SHIP_ASSERT(offsetof(ship_device_info_record, rotation) == 56, "DeviceInfo.rotation");
SHIP_ASSERT(offsetof(ship_device_info_record, alias) == 88, "DeviceInfo.alias");
SHIP_ASSERT(offsetof(ship_device_info_record, group_count) == 160, "DeviceInfo.group_count");
SHIP_ASSERT(sizeof(ship_device_info_record) == 168, "DeviceInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_device_info_record) == 8, "DeviceInfo alignment");
typedef struct {
    uint64_t flags;
} ship_device_status_record;
SHIP_ASSERT(offsetof(ship_device_status_record, flags) == 0, "DeviceStatus.flags");
SHIP_ASSERT(sizeof(ship_device_status_record) == 8, "DeviceStatus size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_device_status_record) == 8, "DeviceStatus alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t sample_present;
    double sample_time_s;
    double acceleration[3];
} ship_accelerometer_reading_record;
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, status) == 0, "AccelerometerReading.status");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, sample_present) == 8, "AccelerometerReading.sample_present");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, sample_time_s) == 16, "AccelerometerReading.sample_time_s");
SHIP_ASSERT(offsetof(ship_accelerometer_reading_record, acceleration) == 24, "AccelerometerReading.acceleration");
SHIP_ASSERT(sizeof(ship_accelerometer_reading_record) == 48, "AccelerometerReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_accelerometer_reading_record) == 8, "AccelerometerReading alignment");
typedef struct {
    double capacity_m3;
} ship_storage_spec_record;
SHIP_ASSERT(offsetof(ship_storage_spec_record, capacity_m3) == 0, "StorageSpec.capacity_m3");
SHIP_ASSERT(sizeof(ship_storage_spec_record) == 8, "StorageSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_storage_spec_record) == 8, "StorageSpec alignment");
typedef struct {
    uint64_t capacity_j;
} ship_battery_spec_record;
SHIP_ASSERT(offsetof(ship_battery_spec_record, capacity_j) == 0, "BatterySpec.capacity_j");
SHIP_ASSERT(sizeof(ship_battery_spec_record) == 8, "BatterySpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_battery_spec_record) == 8, "BatterySpec alignment");
typedef struct {
    uint64_t propellant_resource;
    double max_thrust_n;
    double propellant_units_s;
    double max_power_w;
} ship_engine_spec_record;
SHIP_ASSERT(offsetof(ship_engine_spec_record, propellant_resource) == 0, "EngineSpec.propellant_resource");
SHIP_ASSERT(offsetof(ship_engine_spec_record, max_thrust_n) == 8, "EngineSpec.max_thrust_n");
SHIP_ASSERT(offsetof(ship_engine_spec_record, propellant_units_s) == 16, "EngineSpec.propellant_units_s");
SHIP_ASSERT(offsetof(ship_engine_spec_record, max_power_w) == 24, "EngineSpec.max_power_w");
SHIP_ASSERT(sizeof(ship_engine_spec_record) == 32, "EngineSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_engine_spec_record) == 8, "EngineSpec alignment");
typedef struct {
    ship_device_status_record status;
    double thrust_n;
} ship_engine_reading_record;
SHIP_ASSERT(offsetof(ship_engine_reading_record, status) == 0, "EngineReading.status");
SHIP_ASSERT(offsetof(ship_engine_reading_record, thrust_n) == 8, "EngineReading.thrust_n");
SHIP_ASSERT(sizeof(ship_engine_reading_record) == 16, "EngineReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_engine_reading_record) == 8, "EngineReading alignment");
typedef struct {
    double per_axis_limit_nm;
    double max_power_w;
} ship_torquer_spec_record;
SHIP_ASSERT(offsetof(ship_torquer_spec_record, per_axis_limit_nm) == 0, "TorquerSpec.per_axis_limit_nm");
SHIP_ASSERT(offsetof(ship_torquer_spec_record, max_power_w) == 8, "TorquerSpec.max_power_w");
SHIP_ASSERT(sizeof(ship_torquer_spec_record) == 16, "TorquerSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torquer_spec_record) == 8, "TorquerSpec alignment");
typedef struct {
    ship_device_status_record status;
    double torque_magnitude_nm;
} ship_torquer_reading_record;
SHIP_ASSERT(offsetof(ship_torquer_reading_record, status) == 0, "TorquerReading.status");
SHIP_ASSERT(offsetof(ship_torquer_reading_record, torque_magnitude_nm) == 8, "TorquerReading.torque_magnitude_nm");
SHIP_ASSERT(sizeof(ship_torquer_reading_record) == 16, "TorquerReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torquer_reading_record) == 8, "TorquerReading alignment");
typedef struct {
    uint64_t fuel_resource;
    double max_power_w;
    double fuel_units_s;
    double efficiency;
} ship_generator_spec_record;
SHIP_ASSERT(offsetof(ship_generator_spec_record, fuel_resource) == 0, "GeneratorSpec.fuel_resource");
SHIP_ASSERT(offsetof(ship_generator_spec_record, max_power_w) == 8, "GeneratorSpec.max_power_w");
SHIP_ASSERT(offsetof(ship_generator_spec_record, fuel_units_s) == 16, "GeneratorSpec.fuel_units_s");
SHIP_ASSERT(offsetof(ship_generator_spec_record, efficiency) == 24, "GeneratorSpec.efficiency");
SHIP_ASSERT(sizeof(ship_generator_spec_record) == 32, "GeneratorSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_spec_record) == 8, "GeneratorSpec alignment");
typedef struct {
    ship_device_status_record status;
    double power_w;
} ship_generator_reading_record;
SHIP_ASSERT(offsetof(ship_generator_reading_record, status) == 0, "GeneratorReading.status");
SHIP_ASSERT(offsetof(ship_generator_reading_record, power_w) == 8, "GeneratorReading.power_w");
SHIP_ASSERT(sizeof(ship_generator_reading_record) == 16, "GeneratorReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_reading_record) == 8, "GeneratorReading alignment");
typedef struct {
    double deployed_mass_kg;
    double radiator_area_m2;
    double feed_rate_kg_s;
    double emissivity;
    double sustain_power_w;
} ship_shield_spec_record;
SHIP_ASSERT(offsetof(ship_shield_spec_record, deployed_mass_kg) == 0, "ShieldSpec.deployed_mass_kg");
SHIP_ASSERT(offsetof(ship_shield_spec_record, radiator_area_m2) == 8, "ShieldSpec.radiator_area_m2");
SHIP_ASSERT(offsetof(ship_shield_spec_record, feed_rate_kg_s) == 16, "ShieldSpec.feed_rate_kg_s");
SHIP_ASSERT(offsetof(ship_shield_spec_record, emissivity) == 24, "ShieldSpec.emissivity");
SHIP_ASSERT(offsetof(ship_shield_spec_record, sustain_power_w) == 32, "ShieldSpec.sustain_power_w");
SHIP_ASSERT(sizeof(ship_shield_spec_record) == 40, "ShieldSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_shield_spec_record) == 8, "ShieldSpec alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t state;
    double temperature_k;
    double reserve_kg;
    double reserve_capacity_kg;
    double strength;
    double ablation_kg_s;
    double radiated_power_w;
    double power_w;
} ship_shield_reading_record;
SHIP_ASSERT(offsetof(ship_shield_reading_record, status) == 0, "ShieldReading.status");
SHIP_ASSERT(offsetof(ship_shield_reading_record, state) == 8, "ShieldReading.state");
SHIP_ASSERT(offsetof(ship_shield_reading_record, temperature_k) == 16, "ShieldReading.temperature_k");
SHIP_ASSERT(offsetof(ship_shield_reading_record, reserve_kg) == 24, "ShieldReading.reserve_kg");
SHIP_ASSERT(offsetof(ship_shield_reading_record, reserve_capacity_kg) == 32, "ShieldReading.reserve_capacity_kg");
SHIP_ASSERT(offsetof(ship_shield_reading_record, strength) == 40, "ShieldReading.strength");
SHIP_ASSERT(offsetof(ship_shield_reading_record, ablation_kg_s) == 48, "ShieldReading.ablation_kg_s");
SHIP_ASSERT(offsetof(ship_shield_reading_record, radiated_power_w) == 56, "ShieldReading.radiated_power_w");
SHIP_ASSERT(offsetof(ship_shield_reading_record, power_w) == 64, "ShieldReading.power_w");
SHIP_ASSERT(sizeof(ship_shield_reading_record) == 72, "ShieldReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_shield_reading_record) == 8, "ShieldReading alignment");
typedef struct {
    uint64_t ammunition_resource;
    double projectile_mass_kg;
    double projectile_radius_m;
    double muzzle_speed_m_s;
    double cycle_interval_s;
    double efficiency;
    double dispersion_half_angle_rad;
    double pivot_device_m[3];
    double muzzle_offset_m[3];
    double yaw_min_rad;
    double yaw_max_rad;
    double pitch_min_rad;
    double pitch_max_rad;
    double yaw_rate_rad_s;
    double pitch_rate_rad_s;
    double beam_power_w;
    double beam_range_m;
    uint64_t chemical;
} ship_weapon_spec_record;
SHIP_ASSERT(offsetof(ship_weapon_spec_record, ammunition_resource) == 0, "WeaponSpec.ammunition_resource");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, projectile_mass_kg) == 8, "WeaponSpec.projectile_mass_kg");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, projectile_radius_m) == 16, "WeaponSpec.projectile_radius_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, muzzle_speed_m_s) == 24, "WeaponSpec.muzzle_speed_m_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, cycle_interval_s) == 32, "WeaponSpec.cycle_interval_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, efficiency) == 40, "WeaponSpec.efficiency");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, dispersion_half_angle_rad) == 48, "WeaponSpec.dispersion_half_angle_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pivot_device_m) == 56, "WeaponSpec.pivot_device_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, muzzle_offset_m) == 80, "WeaponSpec.muzzle_offset_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_min_rad) == 104, "WeaponSpec.yaw_min_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_max_rad) == 112, "WeaponSpec.yaw_max_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_min_rad) == 120, "WeaponSpec.pitch_min_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_max_rad) == 128, "WeaponSpec.pitch_max_rad");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, yaw_rate_rad_s) == 136, "WeaponSpec.yaw_rate_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, pitch_rate_rad_s) == 144, "WeaponSpec.pitch_rate_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, beam_power_w) == 152, "WeaponSpec.beam_power_w");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, beam_range_m) == 160, "WeaponSpec.beam_range_m");
SHIP_ASSERT(offsetof(ship_weapon_spec_record, chemical) == 168, "WeaponSpec.chemical");
SHIP_ASSERT(sizeof(ship_weapon_spec_record) == 176, "WeaponSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_spec_record) == 8, "WeaponSpec alignment");
typedef struct {
    double aim_direction[3];
    double aim_angular_velocity_rad_s[3];
    double maximum_pointing_error_rad;
    double valid_until_s;
    uint64_t trigger;
} ship_weapon_setting_record;
SHIP_ASSERT(offsetof(ship_weapon_setting_record, aim_direction) == 0, "WeaponSetting.aim_direction");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, aim_angular_velocity_rad_s) == 24, "WeaponSetting.aim_angular_velocity_rad_s");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, maximum_pointing_error_rad) == 48, "WeaponSetting.maximum_pointing_error_rad");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, valid_until_s) == 56, "WeaponSetting.valid_until_s");
SHIP_ASSERT(offsetof(ship_weapon_setting_record, trigger) == 64, "WeaponSetting.trigger");
SHIP_ASSERT(sizeof(ship_weapon_setting_record) == 72, "WeaponSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_setting_record) == 8, "WeaponSetting alignment");
typedef struct {
    ship_device_status_record status;
    uint64_t inhibit_flags;
    uint64_t ammunition_units;
    uint64_t shots_fired;
    uint64_t battery_energy_j;
    double shot_energy_j;
    double yaw_rad;
    double pitch_rad;
    double next_fire_s;
} ship_weapon_reading_record;
SHIP_ASSERT(offsetof(ship_weapon_reading_record, status) == 0, "WeaponReading.status");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, inhibit_flags) == 8, "WeaponReading.inhibit_flags");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, ammunition_units) == 16, "WeaponReading.ammunition_units");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, shots_fired) == 24, "WeaponReading.shots_fired");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, battery_energy_j) == 32, "WeaponReading.battery_energy_j");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, shot_energy_j) == 40, "WeaponReading.shot_energy_j");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, yaw_rad) == 48, "WeaponReading.yaw_rad");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, pitch_rad) == 56, "WeaponReading.pitch_rad");
SHIP_ASSERT(offsetof(ship_weapon_reading_record, next_fire_s) == 64, "WeaponReading.next_fire_s");
SHIP_ASSERT(sizeof(ship_weapon_reading_record) == 72, "WeaponReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_reading_record) == 8, "WeaponReading alignment");
typedef struct {
    uint64_t contact;
    double maximum_flight_time_s;
} ship_mark_target_request_record;
SHIP_ASSERT(offsetof(ship_mark_target_request_record, contact) == 0, "MarkTargetRequest.contact");
SHIP_ASSERT(offsetof(ship_mark_target_request_record, maximum_flight_time_s) == 8, "MarkTargetRequest.maximum_flight_time_s");
SHIP_ASSERT(sizeof(ship_mark_target_request_record) == 16, "MarkTargetRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_mark_target_request_record) == 8, "MarkTargetRequest alignment");
typedef struct {
    double valid_until_s;
    uint64_t mode;
    uint64_t target_contact;
    ship_text256 reason;
} ship_weapons_state_record;
SHIP_ASSERT(offsetof(ship_weapons_state_record, valid_until_s) == 0, "WeaponsState.valid_until_s");
SHIP_ASSERT(offsetof(ship_weapons_state_record, mode) == 8, "WeaponsState.mode");
SHIP_ASSERT(offsetof(ship_weapons_state_record, target_contact) == 16, "WeaponsState.target_contact");
SHIP_ASSERT(offsetof(ship_weapons_state_record, reason) == 24, "WeaponsState.reason");
SHIP_ASSERT(sizeof(ship_weapons_state_record) == 288, "WeaponsState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapons_state_record) == 8, "WeaponsState alignment");
typedef struct {
    uint64_t device;
    uint64_t aim_marker;
    uint64_t solution_flags;
    double time_of_flight_s;
    double pointing_error_rad;
    ship_weapon_reading_record reading;
} ship_weapon_instrument_record;
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, device) == 0, "WeaponInstrument.device");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, aim_marker) == 8, "WeaponInstrument.aim_marker");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, solution_flags) == 16, "WeaponInstrument.solution_flags");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, time_of_flight_s) == 24, "WeaponInstrument.time_of_flight_s");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, pointing_error_rad) == 32, "WeaponInstrument.pointing_error_rad");
SHIP_ASSERT(offsetof(ship_weapon_instrument_record, reading) == 40, "WeaponInstrument.reading");
SHIP_ASSERT(sizeof(ship_weapon_instrument_record) == 112, "WeaponInstrument size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_weapon_instrument_record) == 8, "WeaponInstrument alignment");
typedef struct {
    double max_range_m;
    double power_w;
} ship_sensor_spec_record;
SHIP_ASSERT(offsetof(ship_sensor_spec_record, max_range_m) == 0, "SensorSpec.max_range_m");
SHIP_ASSERT(offsetof(ship_sensor_spec_record, power_w) == 8, "SensorSpec.power_w");
SHIP_ASSERT(sizeof(ship_sensor_spec_record) == 16, "SensorSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_sensor_spec_record) == 8, "SensorSpec alignment");
typedef struct {
    ship_device_status_record status;
    double range_m;
} ship_sensor_reading_record;
SHIP_ASSERT(offsetof(ship_sensor_reading_record, status) == 0, "SensorReading.status");
SHIP_ASSERT(offsetof(ship_sensor_reading_record, range_m) == 8, "SensorReading.range_m");
SHIP_ASSERT(sizeof(ship_sensor_reading_record) == 16, "SensorReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_sensor_reading_record) == 8, "SensorReading alignment");
typedef struct {
    double fraction;
} ship_throttle_setting_record;
SHIP_ASSERT(offsetof(ship_throttle_setting_record, fraction) == 0, "ThrottleSetting.fraction");
SHIP_ASSERT(sizeof(ship_throttle_setting_record) == 8, "ThrottleSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_throttle_setting_record) == 8, "ThrottleSetting alignment");
typedef struct {
    double torque_nm[3];
} ship_torque_setting_record;
SHIP_ASSERT(offsetof(ship_torque_setting_record, torque_nm) == 0, "TorqueSetting.torque_nm");
SHIP_ASSERT(sizeof(ship_torque_setting_record) == 24, "TorqueSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_torque_setting_record) == 8, "TorqueSetting alignment");
typedef struct {
    double fraction;
} ship_generator_demand_setting_record;
SHIP_ASSERT(offsetof(ship_generator_demand_setting_record, fraction) == 0, "GeneratorDemandSetting.fraction");
SHIP_ASSERT(sizeof(ship_generator_demand_setting_record) == 8, "GeneratorDemandSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_generator_demand_setting_record) == 8, "GeneratorDemandSetting alignment");
typedef struct {
    uint64_t enabled;
} ship_enabled_setting_record;
SHIP_ASSERT(offsetof(ship_enabled_setting_record, enabled) == 0, "EnabledSetting.enabled");
SHIP_ASSERT(sizeof(ship_enabled_setting_record) == 8, "EnabledSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_enabled_setting_record) == 8, "EnabledSetting alignment");
typedef struct {
    uint64_t id;
    ship_text64 key;
    double unit_mass_kg;
    double unit_volume_m3;
} ship_resource_info_record;
SHIP_ASSERT(offsetof(ship_resource_info_record, id) == 0, "ResourceInfo.id");
SHIP_ASSERT(offsetof(ship_resource_info_record, key) == 8, "ResourceInfo.key");
SHIP_ASSERT(offsetof(ship_resource_info_record, unit_mass_kg) == 80, "ResourceInfo.unit_mass_kg");
SHIP_ASSERT(offsetof(ship_resource_info_record, unit_volume_m3) == 88, "ResourceInfo.unit_volume_m3");
SHIP_ASSERT(sizeof(ship_resource_info_record) == 96, "ResourceInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_resource_info_record) == 8, "ResourceInfo alignment");
typedef struct {
    uint64_t units;
} ship_resource_amount_record;
SHIP_ASSERT(offsetof(ship_resource_amount_record, units) == 0, "ResourceAmount.units");
SHIP_ASSERT(sizeof(ship_resource_amount_record) == 8, "ResourceAmount size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_resource_amount_record) == 8, "ResourceAmount alignment");
typedef struct {
    uint64_t id;
    uint64_t kind;
    double radius_m;
    double position_m[3];
    double velocity_m_s[3];
} ship_contact_record;
SHIP_ASSERT(offsetof(ship_contact_record, id) == 0, "Contact.id");
SHIP_ASSERT(offsetof(ship_contact_record, kind) == 8, "Contact.kind");
SHIP_ASSERT(offsetof(ship_contact_record, radius_m) == 16, "Contact.radius_m");
SHIP_ASSERT(offsetof(ship_contact_record, position_m) == 24, "Contact.position_m");
SHIP_ASSERT(offsetof(ship_contact_record, velocity_m_s) == 48, "Contact.velocity_m_s");
SHIP_ASSERT(sizeof(ship_contact_record) == 72, "Contact size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_record) == 8, "Contact alignment");
typedef struct {
    uint64_t id;
    uint64_t kind;
    uint64_t payload_bytes;
} ship_request_info_record;
SHIP_ASSERT(offsetof(ship_request_info_record, id) == 0, "RequestInfo.id");
SHIP_ASSERT(offsetof(ship_request_info_record, kind) == 8, "RequestInfo.kind");
SHIP_ASSERT(offsetof(ship_request_info_record, payload_bytes) == 16, "RequestInfo.payload_bytes");
SHIP_ASSERT(sizeof(ship_request_info_record) == 24, "RequestInfo size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_request_info_record) == 8, "RequestInfo alignment");
typedef struct {
    double throttle;
    double steering[3];
} ship_manual_request_record;
SHIP_ASSERT(offsetof(ship_manual_request_record, throttle) == 0, "ManualRequest.throttle");
SHIP_ASSERT(offsetof(ship_manual_request_record, steering) == 8, "ManualRequest.steering");
SHIP_ASSERT(sizeof(ship_manual_request_record) == 32, "ManualRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_manual_request_record) == 8, "ManualRequest alignment");
typedef struct {
    double direction[3];
} ship_direction_request_record;
SHIP_ASSERT(offsetof(ship_direction_request_record, direction) == 0, "DirectionRequest.direction");
SHIP_ASSERT(sizeof(ship_direction_request_record) == 24, "DirectionRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_direction_request_record) == 8, "DirectionRequest alignment");
typedef struct {
    uint64_t contact;
} ship_contact_request_record;
SHIP_ASSERT(offsetof(ship_contact_request_record, contact) == 0, "ContactRequest.contact");
SHIP_ASSERT(sizeof(ship_contact_request_record) == 8, "ContactRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contact_request_record) == 8, "ContactRequest alignment");
typedef struct {
    double throttle_limit;
    double stand_off_m;
} ship_navigation_request_record;
SHIP_ASSERT(offsetof(ship_navigation_request_record, throttle_limit) == 0, "NavigationRequest.throttle_limit");
SHIP_ASSERT(offsetof(ship_navigation_request_record, stand_off_m) == 8, "NavigationRequest.stand_off_m");
SHIP_ASSERT(sizeof(ship_navigation_request_record) == 16, "NavigationRequest size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_navigation_request_record) == 8, "NavigationRequest alignment");
typedef struct {
    uint64_t id;
    uint64_t role;
    double valid_until_s;
    ship_text64 label;
} ship_spatial_meta_record;
SHIP_ASSERT(offsetof(ship_spatial_meta_record, id) == 0, "SpatialMeta.id");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, role) == 8, "SpatialMeta.role");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, valid_until_s) == 16, "SpatialMeta.valid_until_s");
SHIP_ASSERT(offsetof(ship_spatial_meta_record, label) == 24, "SpatialMeta.label");
SHIP_ASSERT(sizeof(ship_spatial_meta_record) == 96, "SpatialMeta size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_meta_record) == 8, "SpatialMeta alignment");
typedef struct {
    uint64_t kind;
    uint64_t reference;
    double origin_velocity_m_s[3];
} ship_spatial_frame_record;
SHIP_ASSERT(offsetof(ship_spatial_frame_record, kind) == 0, "SpatialFrame.kind");
SHIP_ASSERT(offsetof(ship_spatial_frame_record, reference) == 8, "SpatialFrame.reference");
SHIP_ASSERT(offsetof(ship_spatial_frame_record, origin_velocity_m_s) == 16, "SpatialFrame.origin_velocity_m_s");
SHIP_ASSERT(sizeof(ship_spatial_frame_record) == 40, "SpatialFrame size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_frame_record) == 8, "SpatialFrame alignment");
typedef struct {
    ship_spatial_meta_record meta;
    ship_spatial_frame_record frame;
    double offset_m[3];
    uint64_t time_mode;
    double time_s;
} ship_spatial_marker_record;
SHIP_ASSERT(offsetof(ship_spatial_marker_record, meta) == 0, "SpatialMarker.meta");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, frame) == 96, "SpatialMarker.frame");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, offset_m) == 136, "SpatialMarker.offset_m");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, time_mode) == 160, "SpatialMarker.time_mode");
SHIP_ASSERT(offsetof(ship_spatial_marker_record, time_s) == 168, "SpatialMarker.time_s");
SHIP_ASSERT(sizeof(ship_spatial_marker_record) == 176, "SpatialMarker size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_marker_record) == 8, "SpatialMarker alignment");
typedef struct {
    ship_spatial_meta_record meta;
    ship_spatial_frame_record frame;
    uint64_t kind;
    uint64_t subject_contact;
} ship_spatial_path_record;
SHIP_ASSERT(offsetof(ship_spatial_path_record, meta) == 0, "SpatialPath.meta");
SHIP_ASSERT(offsetof(ship_spatial_path_record, frame) == 96, "SpatialPath.frame");
SHIP_ASSERT(offsetof(ship_spatial_path_record, kind) == 136, "SpatialPath.kind");
SHIP_ASSERT(offsetof(ship_spatial_path_record, subject_contact) == 144, "SpatialPath.subject_contact");
SHIP_ASSERT(sizeof(ship_spatial_path_record) == 152, "SpatialPath size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_path_record) == 8, "SpatialPath alignment");
typedef struct {
    double time_s;
    double position_m[3];
} ship_spatial_vertex_record;
SHIP_ASSERT(offsetof(ship_spatial_vertex_record, time_s) == 0, "SpatialVertex.time_s");
SHIP_ASSERT(offsetof(ship_spatial_vertex_record, position_m) == 8, "SpatialVertex.position_m");
SHIP_ASSERT(sizeof(ship_spatial_vertex_record) == 32, "SpatialVertex size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_spatial_vertex_record) == 8, "SpatialVertex alignment");
typedef struct {
    double valid_until_s;
    uint64_t mode;
    uint64_t present;
    double reference[4];
    double control_error;
} ship_attitude_state_record;
SHIP_ASSERT(offsetof(ship_attitude_state_record, valid_until_s) == 0, "AttitudeState.valid_until_s");
SHIP_ASSERT(offsetof(ship_attitude_state_record, mode) == 8, "AttitudeState.mode");
SHIP_ASSERT(offsetof(ship_attitude_state_record, present) == 16, "AttitudeState.present");
SHIP_ASSERT(offsetof(ship_attitude_state_record, reference) == 24, "AttitudeState.reference");
SHIP_ASSERT(offsetof(ship_attitude_state_record, control_error) == 56, "AttitudeState.control_error");
SHIP_ASSERT(sizeof(ship_attitude_state_record) == 64, "AttitudeState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_attitude_state_record) == 8, "AttitudeState alignment");
typedef struct {
    double valid_until_s;
    uint64_t status;
    uint64_t target_contact;
    uint64_t own_path;
    uint64_t target_path;
    uint64_t present;
    double throttle_limit;
    double throttle;
    double stand_off_m;
    double approach_speed_limit_m_s;
    double braking_distance_m;
    double arrival_time_s;
    double predicted_fuel_kg;
    ship_text256 reason;
} ship_navigation_state_record;
SHIP_ASSERT(offsetof(ship_navigation_state_record, valid_until_s) == 0, "NavigationState.valid_until_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, status) == 8, "NavigationState.status");
SHIP_ASSERT(offsetof(ship_navigation_state_record, target_contact) == 16, "NavigationState.target_contact");
SHIP_ASSERT(offsetof(ship_navigation_state_record, own_path) == 24, "NavigationState.own_path");
SHIP_ASSERT(offsetof(ship_navigation_state_record, target_path) == 32, "NavigationState.target_path");
SHIP_ASSERT(offsetof(ship_navigation_state_record, present) == 40, "NavigationState.present");
SHIP_ASSERT(offsetof(ship_navigation_state_record, throttle_limit) == 48, "NavigationState.throttle_limit");
SHIP_ASSERT(offsetof(ship_navigation_state_record, throttle) == 56, "NavigationState.throttle");
SHIP_ASSERT(offsetof(ship_navigation_state_record, stand_off_m) == 64, "NavigationState.stand_off_m");
SHIP_ASSERT(offsetof(ship_navigation_state_record, approach_speed_limit_m_s) == 72, "NavigationState.approach_speed_limit_m_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, braking_distance_m) == 80, "NavigationState.braking_distance_m");
SHIP_ASSERT(offsetof(ship_navigation_state_record, arrival_time_s) == 88, "NavigationState.arrival_time_s");
SHIP_ASSERT(offsetof(ship_navigation_state_record, predicted_fuel_kg) == 96, "NavigationState.predicted_fuel_kg");
SHIP_ASSERT(offsetof(ship_navigation_state_record, reason) == 104, "NavigationState.reason");
SHIP_ASSERT(sizeof(ship_navigation_state_record) == 368, "NavigationState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_navigation_state_record) == 8, "NavigationState alignment");
typedef struct {
    double valid_until_s;
    uint64_t selected_contact;
} ship_contacts_state_record;
SHIP_ASSERT(offsetof(ship_contacts_state_record, valid_until_s) == 0, "ContactsState.valid_until_s");
SHIP_ASSERT(offsetof(ship_contacts_state_record, selected_contact) == 8, "ContactsState.selected_contact");
SHIP_ASSERT(sizeof(ship_contacts_state_record) == 16, "ContactsState size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_contacts_state_record) == 8, "ContactsState alignment");
typedef struct {
    uint64_t id;
    uint64_t width;
    uint64_t height;
    ship_text64 title;
} ship_screen_definition_record;
SHIP_ASSERT(offsetof(ship_screen_definition_record, id) == 0, "ScreenDefinition.id");
SHIP_ASSERT(offsetof(ship_screen_definition_record, width) == 8, "ScreenDefinition.width");
SHIP_ASSERT(offsetof(ship_screen_definition_record, height) == 16, "ScreenDefinition.height");
SHIP_ASSERT(offsetof(ship_screen_definition_record, title) == 24, "ScreenDefinition.title");
SHIP_ASSERT(sizeof(ship_screen_definition_record) == 96, "ScreenDefinition size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_definition_record) == 8, "ScreenDefinition alignment");
typedef struct {
    uint64_t id;
    uint64_t background;
} ship_screen_frame_record;
SHIP_ASSERT(offsetof(ship_screen_frame_record, id) == 0, "ScreenFrame.id");
SHIP_ASSERT(offsetof(ship_screen_frame_record, background) == 8, "ScreenFrame.background");
SHIP_ASSERT(sizeof(ship_screen_frame_record) == 16, "ScreenFrame size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_frame_record) == 8, "ScreenFrame alignment");
typedef struct {
    uint64_t color;
    int64_t x;
    int64_t y;
} ship_screen_pixel_record;
SHIP_ASSERT(offsetof(ship_screen_pixel_record, color) == 0, "ScreenPixel.color");
SHIP_ASSERT(offsetof(ship_screen_pixel_record, x) == 8, "ScreenPixel.x");
SHIP_ASSERT(offsetof(ship_screen_pixel_record, y) == 16, "ScreenPixel.y");
SHIP_ASSERT(sizeof(ship_screen_pixel_record) == 24, "ScreenPixel size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_pixel_record) == 8, "ScreenPixel alignment");
typedef struct {
    uint64_t color;
    int64_t x;
    int64_t y;
} ship_screen_text_record;
SHIP_ASSERT(offsetof(ship_screen_text_record, color) == 0, "ScreenText.color");
SHIP_ASSERT(offsetof(ship_screen_text_record, x) == 8, "ScreenText.x");
SHIP_ASSERT(offsetof(ship_screen_text_record, y) == 16, "ScreenText.y");
SHIP_ASSERT(sizeof(ship_screen_text_record) == 24, "ScreenText size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_text_record) == 8, "ScreenText alignment");
typedef struct {
    uint64_t color;
    int64_t x1;
    int64_t y1;
    int64_t x2;
    int64_t y2;
} ship_screen_line_record;
SHIP_ASSERT(offsetof(ship_screen_line_record, color) == 0, "ScreenLine.color");
SHIP_ASSERT(offsetof(ship_screen_line_record, x1) == 8, "ScreenLine.x1");
SHIP_ASSERT(offsetof(ship_screen_line_record, y1) == 16, "ScreenLine.y1");
SHIP_ASSERT(offsetof(ship_screen_line_record, x2) == 24, "ScreenLine.x2");
SHIP_ASSERT(offsetof(ship_screen_line_record, y2) == 32, "ScreenLine.y2");
SHIP_ASSERT(sizeof(ship_screen_line_record) == 40, "ScreenLine size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_line_record) == 8, "ScreenLine alignment");
typedef struct {
    uint64_t color;
} ship_screen_polyline_record;
SHIP_ASSERT(offsetof(ship_screen_polyline_record, color) == 0, "ScreenPolyline.color");
SHIP_ASSERT(sizeof(ship_screen_polyline_record) == 8, "ScreenPolyline size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_polyline_record) == 8, "ScreenPolyline alignment");
typedef struct {
    int64_t x;
    int64_t y;
} ship_screen_point_record;
SHIP_ASSERT(offsetof(ship_screen_point_record, x) == 0, "ScreenPoint.x");
SHIP_ASSERT(offsetof(ship_screen_point_record, y) == 8, "ScreenPoint.y");
SHIP_ASSERT(sizeof(ship_screen_point_record) == 16, "ScreenPoint size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_point_record) == 8, "ScreenPoint alignment");
typedef struct {
    uint64_t color;
    uint64_t filled;
    int64_t x;
    int64_t y;
    uint64_t width;
    uint64_t height;
} ship_screen_rectangle_record;
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, color) == 0, "ScreenRectangle.color");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, filled) == 8, "ScreenRectangle.filled");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, x) == 16, "ScreenRectangle.x");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, y) == 24, "ScreenRectangle.y");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, width) == 32, "ScreenRectangle.width");
SHIP_ASSERT(offsetof(ship_screen_rectangle_record, height) == 40, "ScreenRectangle.height");
SHIP_ASSERT(sizeof(ship_screen_rectangle_record) == 48, "ScreenRectangle size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_rectangle_record) == 8, "ScreenRectangle alignment");
typedef struct {
    uint64_t color;
    uint64_t filled;
    int64_t cx;
    int64_t cy;
    uint64_t rx;
    uint64_t ry;
} ship_screen_ellipse_record;
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, color) == 0, "ScreenEllipse.color");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, filled) == 8, "ScreenEllipse.filled");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, cx) == 16, "ScreenEllipse.cx");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, cy) == 24, "ScreenEllipse.cy");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, rx) == 32, "ScreenEllipse.rx");
SHIP_ASSERT(offsetof(ship_screen_ellipse_record, ry) == 40, "ScreenEllipse.ry");
SHIP_ASSERT(sizeof(ship_screen_ellipse_record) == 48, "ScreenEllipse size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_ellipse_record) == 8, "ScreenEllipse alignment");
typedef struct {
    uint64_t id;
    uint64_t screen;
    uint64_t kind;
    uint64_t code;
    uint64_t modifiers;
    double x;
    double y;
    ship_text64 text;
} ship_screen_event_record;
SHIP_ASSERT(offsetof(ship_screen_event_record, id) == 0, "ScreenEvent.id");
SHIP_ASSERT(offsetof(ship_screen_event_record, screen) == 8, "ScreenEvent.screen");
SHIP_ASSERT(offsetof(ship_screen_event_record, kind) == 16, "ScreenEvent.kind");
SHIP_ASSERT(offsetof(ship_screen_event_record, code) == 24, "ScreenEvent.code");
SHIP_ASSERT(offsetof(ship_screen_event_record, modifiers) == 32, "ScreenEvent.modifiers");
SHIP_ASSERT(offsetof(ship_screen_event_record, x) == 40, "ScreenEvent.x");
SHIP_ASSERT(offsetof(ship_screen_event_record, y) == 48, "ScreenEvent.y");
SHIP_ASSERT(offsetof(ship_screen_event_record, text) == 56, "ScreenEvent.text");
SHIP_ASSERT(sizeof(ship_screen_event_record) == 128, "ScreenEvent size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_screen_event_record) == 8, "ScreenEvent alignment");
typedef struct {
    uint64_t propellant_resource;
    double per_axis_thrust_n;
    double per_axis_propellant_units_s;
    double per_axis_power_w;
} ship_rcs_spec_record;
SHIP_ASSERT(offsetof(ship_rcs_spec_record, propellant_resource) == 0, "RcsSpec.propellant_resource");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_thrust_n) == 8, "RcsSpec.per_axis_thrust_n");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_propellant_units_s) == 16, "RcsSpec.per_axis_propellant_units_s");
SHIP_ASSERT(offsetof(ship_rcs_spec_record, per_axis_power_w) == 24, "RcsSpec.per_axis_power_w");
SHIP_ASSERT(sizeof(ship_rcs_spec_record) == 32, "RcsSpec size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_spec_record) == 8, "RcsSpec alignment");
typedef struct {
    double thrust_n[3];
} ship_rcs_setting_record;
SHIP_ASSERT(offsetof(ship_rcs_setting_record, thrust_n) == 0, "RcsSetting.thrust_n");
SHIP_ASSERT(sizeof(ship_rcs_setting_record) == 24, "RcsSetting size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_setting_record) == 8, "RcsSetting alignment");
typedef struct {
    ship_device_status_record status;
    double thrust_n[3];
} ship_rcs_reading_record;
SHIP_ASSERT(offsetof(ship_rcs_reading_record, status) == 0, "RcsReading.status");
SHIP_ASSERT(offsetof(ship_rcs_reading_record, thrust_n) == 8, "RcsReading.thrust_n");
SHIP_ASSERT(sizeof(ship_rcs_reading_record) == 32, "RcsReading size");
SHIP_ASSERT(SHIP_ALIGNOF(ship_rcs_reading_record) == 8, "RcsReading alignment");
SHIP_IMPORT("persistent_read") int32_t ship_persistent_read(void * output, uint32_t capacity);
SHIP_IMPORT("persistent_write") int32_t ship_persistent_write(const void * input, uint32_t length);
SHIP_IMPORT("world_query") int32_t ship_world_query(const void * input, uint32_t bytes, void * out, uint32_t capacity);
SHIP_IMPORT("world_command") int32_t ship_world_command(const void * input, uint32_t bytes);
SHIP_IMPORT("tick_read") int32_t ship_tick_read(void * out, uint32_t bytes);
SHIP_IMPORT("budget_read") int32_t ship_budget_read(void * out, uint32_t bytes);
SHIP_IMPORT("flight_read") int32_t ship_flight_read(void * out, uint32_t bytes);
SHIP_IMPORT("ship_resources_read") int32_t ship_ship_resources_read(void * out, uint32_t bytes);
SHIP_IMPORT("tick_set_interval") int32_t ship_tick_set_interval(double seconds);
SHIP_IMPORT("snapshot_keep") int32_t ship_snapshot_keep(uint64_t snapshot);
SHIP_IMPORT("snapshot_drop") int32_t ship_snapshot_drop(uint64_t snapshot);
SHIP_IMPORT("device_info") int32_t ship_device_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("device_group_read") int32_t ship_device_group_read(uint64_t device, uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("device_spec") int32_t ship_device_spec(uint64_t device, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("device_read") int32_t ship_device_read(uint64_t device, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("device_write") int32_t ship_device_write(uint64_t device, uint64_t setting, const void * input, uint32_t bytes);
SHIP_IMPORT("resource_info") int32_t ship_resource_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("resource_read") int32_t ship_resource_read(uint64_t resource, void * out, uint32_t bytes);
SHIP_IMPORT("sensor_scan") int32_t ship_sensor_scan(uint64_t sensor, uint32_t maximum, void * contacts, uint32_t contacts_bytes);
SHIP_IMPORT("contact_label") int32_t ship_contact_label(uint64_t contact, void * out, uint32_t bytes);
SHIP_IMPORT("request_info") int32_t ship_request_info(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("request_read") int32_t ship_request_read(uint32_t index, uint64_t expected_kind, void * out, uint32_t bytes);
SHIP_IMPORT("request_reply") int32_t ship_request_reply(uint64_t request, uint64_t result, const void * message, uint32_t message_bytes);
SHIP_IMPORT("instrument_weapons_put") int32_t ship_instrument_weapons_put(const void * state_pointer, uint32_t state_bytes, const void * weapons_pointer, uint32_t weapon_count);
SHIP_IMPORT("instrument_attitude_put") int32_t ship_instrument_attitude_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_navigation_put") int32_t ship_instrument_navigation_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_contacts_put") int32_t ship_instrument_contacts_put(const void * input, uint32_t bytes);
SHIP_IMPORT("instrument_clear") int32_t ship_instrument_clear(uint64_t kind);
SHIP_IMPORT("spatial_marker_put") int32_t ship_spatial_marker_put(const void * marker, uint32_t marker_bytes);
SHIP_IMPORT("spatial_path_put") int32_t ship_spatial_path_put(const void * path, uint32_t path_bytes, const void * vertices, uint32_t vertex_count);
SHIP_IMPORT("spatial_remove") int32_t ship_spatial_remove(uint64_t id);
SHIP_IMPORT("spatial_clear") int32_t ship_spatial_clear(void);
SHIP_IMPORT("screen_define") int32_t ship_screen_define(const void * input, uint32_t bytes);
SHIP_IMPORT("screen_remove") int32_t ship_screen_remove(uint64_t screen);
SHIP_IMPORT("screen_begin") int32_t ship_screen_begin(const void * input, uint32_t bytes);
SHIP_IMPORT("screen_draw") int32_t ship_screen_draw(uint64_t screen, uint64_t kind, const void * parameters, uint32_t parameter_bytes, const void * payload, uint32_t payload_bytes);
SHIP_IMPORT("screen_button") int32_t ship_screen_button(uint64_t screen, uint64_t key, const void * label, uint32_t label_bytes);
SHIP_IMPORT("screen_end") int32_t ship_screen_end(uint64_t screen);
SHIP_IMPORT("screen_event_read") int32_t ship_screen_event_read(uint32_t index, void * out, uint32_t bytes);
SHIP_IMPORT("screen_event_ack") int32_t ship_screen_event_ack(uint64_t event);
/* Guest exports: uint32_t ship_api_version(void); void ship_tick(void); memory. */
#ifdef __cplusplus
}
#endif
#endif
