[package]
name = "osg-ui"
version.workspace = true
edition.workspace = true

[features]
dynamic_linking = ["dep:bevy_dylib"]

[dependencies]
serde.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
egui_flex = "0.8.0"
osg-model = { path = "../osg-model" }
osg-ship-api = { path = "../osg-ship-api" }
osg-ships = { path = "../osg-ships" }
skrifa = { version = "0.44.0", default-features = false, features = ["std"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_dylib = { workspace = true, optional = true }
