"""Build the fixed slip ring and matching compound occupancy; run with Blender -b -P."""
import importlib.util
import math
from pathlib import Path

import bpy
from mathutils import Matrix, Vector

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("geometry", Path(__file__).with_name("micropulse_engine.py"))
geo = importlib.util.module_from_spec(spec)
spec.loader.exec_module(geo)

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)
geo.collection = bpy.context.scene.collection
steel = geo.material("Slip titanium", (0.22, 0.28, 0.34), 0.8, 0.3)
armor = geo.material("Slip ceramic", (0.055, 0.075, 0.1), 0.35, 0.6)
trim = geo.material("Slip silver", (0.5, 0.56, 0.62), 0.7, 0.3)
emitter = geo.material("Slip emitter", (0.04, 0.45, 0.65), 0.3, 0.25)
shader = emitter.node_tree.nodes.get("Principled BSDF")
shader.inputs["Emission Color"].default_value = (0.04, 0.55, 1.0, 1.0)
shader.inputs["Emission Strength"].default_value = 1.0

geo.ring("Confinement housing", 7.0, 0.0, 2.0, 1.8, armor)
for z in [-0.9, 0.9]:
    geo.ring("Outer structural rim", 7.85, z, 0.28, 0.2, steel)
    geo.ring("Inner structural rim", 6.14, z, 0.28, 0.2, trim)
    geo.ring("slip_emitter", 6.5, z, 0.23, 0.15, emitter)
    geo.ring("slip_emitter", 7.45, z, 0.09, 0.15, emitter)
for i in range(24):
    angle = math.tau * i / 24
    geo.beam("Radial coil brace", geo.radial(6.25, angle, -0.95),
             geo.radial(7.75, angle, -0.95), 0.045, trim, 6)
    geo.beam("Radial coil brace", geo.radial(6.25, angle, 0.95),
             geo.radial(7.75, angle, 0.95), 0.045, trim, 6)

def box(name, low, high, surface):
    vertices = [(x, y, z) for x in [low[0], high[0]]
                for y in [low[1], high[1]] for z in [low[2], high[2]]]
    return geo.mesh(name, vertices, [(0, 1, 3, 2), (4, 6, 7, 5),
                    (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)], surface)

box("Hull mounting pylon", (-0.65, -6.5, -0.75), (0.65, -2.0, 0.75), steel)
box("Mounting collar", (-0.9, -2.3, -0.9), (0.9, -2.0, 0.9), trim)

# The geometry helpers use Z as the drive axis. Convert to Blender coordinates
# before glTF's Y-up conversion so the exported ring remains in the ship's XY plane.
conversion = Matrix.Rotation(math.pi / 2, 4, "X")
for obj in bpy.context.scene.objects:
    if obj.type == "MESH":
        obj.data.transform(conversion)
        obj.select_set(True)

output = ROOT / "assets/models/parts/slipdrive-ring-16m.glb"
bpy.ops.export_scene.gltf(filepath=str(output), export_format="GLB", use_selection=True,
                          export_apply=True, export_extras=True)

# Conservative sector boxes leave the bore empty and include the mounting pylon.
boxes = []
for i in range(32):
    angles = [math.tau * (i + step / 8) / 32 for step in range(9)]
    points = [(r * math.cos(a), r * math.sin(a)) for r in [6.0, 8.0] for a in angles]
    low = [min(p[0] for p in points), min(p[1] for p in points), -1.0]
    high = [max(p[0] for p in points), max(p[1] for p in points), 1.0]
    boxes.append((low, high))
boxes.extend([([-0.65, -6.5, -0.75], [0.65, -2.0, 0.75]),
              ([-0.9, -2.3, -0.9], [0.9, -2.0, 0.9])])
encoded = ", ".join("{ min = [" + ", ".join(f"{v:.6f}" for v in low)
                    + "], max = [" + ", ".join(f"{v:.6f}" for v in high) + "] }"
                    for low, high in boxes)
catalogue = ROOT / "crates/osg-ships/data/catalogue.toml"
lines = catalogue.read_text().splitlines()
marker = lines.index("# Ring collision boxes are generated by tools/art/slipdrive.py.")
lines[marker + 1] = 'collision = { shape = "compound", boxes = [' + encoded + '] }'
catalogue.write_text("\n".join(lines) + "\n")
