[package]
name = "osg-example-controller"
version.workspace = true
edition.workspace = true

[features]
default = ["firmware"]
firmware = []

[dependencies]
serde.workspace = true
osg-model = { path = "../osg-model" }
postcard = { version = "1.1.3", features = ["alloc"] }
glam = "0.32.1"
osg-ship-api = { path = "../osg-ship-api" }

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "custom_screen"
crate-type = ["cdylib"]
