#!/usr/bin/env python3
"""Generate C/AssemblyScript bindings from the allocation-free Rust ABI records."""
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
API = ROOT / "crates/toy-sim-ship-api"
source = "\n".join(
    (API / "src" / filename).read_text()
    for filename in ("abi.rs", "world.rs", "world_intel.rs", "services.rs")
)
import_module = re.search(r'pub const IMPORT_MODULE: &str = "([^"]+)";', source).group(1)
text_sizes = {"Text" + n: int(n) for n in re.findall(r"pub type Text(\d+) = Text<\d+>;", source)}
records = {}
for name, body in re.findall(r"pub struct (\w+) \{([^}]+)\}", source):
    records[name] = re.findall(r"pub (\w+):\s*([^,]+),", body)
for name, body in re.findall(r"record!\(\s*(\w+)\s*\{([^}]+)\}\s*\);", source):
    records[name] = re.findall(r"(\w+):\s*([^,]+)(?:,|$)", body.strip())
sizes = {name: n + 8 for name, n in text_sizes.items()}
alignments = {name: 8 for name in text_sizes}
primitives = {
    "u8": (1, "uint8_t"), "u32": (4, "uint32_t"), "i32": (4, "int32_t"),
    "u64": (8, "uint64_t"), "i64": (8, "int64_t"), "f64": (8, "double"),
}
def normalize(ty):
    ty = re.sub(r"\bText\s*<\s*(\d+)\s*>", r"Text\1", ty.strip())
    return ty.rsplit("::", 1)[-1]
def size(ty):
    ty = normalize(ty)
    if ty.startswith("["):
        elem, count = ty[1:-1].rsplit(";", 1)
        return size(elem) * int(count)
    return sizes[ty] if ty in sizes else primitives[ty][0]
def alignment(ty):
    ty = normalize(ty)
    if ty.startswith("["):
        return alignment(ty[1:-1].rsplit(";", 1)[0])
    return alignments[ty] if ty in alignments else primitives[ty][0]
def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
def cfield(name, ty):
    ty = normalize(ty)
    if ty.startswith("["):
        elem, count = ty[1:-1].rsplit(";", 1)
        return cfield(name + "[" + count.strip() + "]", elem)
    cty = "ship_text" + ty[4:] if ty in text_sizes else ("ship_" + snake(ty) + "_record" if ty in records else primitives[ty][1])
    return f"{cty} {name};"
constants = re.findall(r"pub const (\w+): (u32|i32|u64) = (-?\d+);", source)
c = '''/* Generated by tools/generate_ship_bindings.py. wasm32, little endian. */
#ifndef TOY_SHIP_H
#define TOY_SHIP_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
#define SHIP_ASSERT static_assert
#define SHIP_ALIGNOF alignof
extern "C" {
#else
#define SHIP_ASSERT _Static_assert
#define SHIP_ALIGNOF _Alignof
#endif
#if defined(__wasm__)
#define SHIP_IMPORT(name) __attribute__((import_module("__IMPORT_MODULE__"), import_name(name)))
#else
#define SHIP_IMPORT(name)
#endif
'''
a = '// Generated by tools/generate_ship_bindings.py. Use raw buffers, not managed object layouts.\n'
for name, ty, value in constants:
    cname = "SHIP_API_VERSION" if name == "VERSION" else "SHIP_" + name
    c += f"#define {cname} ({value})\n"
    a += f"export const {name}: {ty} = {value};\n"
for name, n in text_sizes.items():
    c += f"typedef struct {{ uint64_t len; uint8_t bytes[{n}]; }} ship_text{n};\n"
    c += f'SHIP_ASSERT(sizeof(ship_text{n}) == {n+8}, "text layout");\n'
    c += f'SHIP_ASSERT(SHIP_ALIGNOF(ship_text{n}) == 8, "text alignment");\n'
    a += f"export const TEXT{n}_SIZE: u32 = {n+8};\n"
for name, fields in records.items():
    ctype = "ship_" + snake(name) + "_record"
    c += "typedef struct {\n" + "\n".join("    " + cfield(f, t) for f, t in fields) + f"\n}} {ctype};\n"
    offset = 0
    record_alignment = max(alignment(ty) for _, ty in fields)
    for field, ty in fields:
        if offset % alignment(ty):
            raise ValueError(f"{name}.{field} needs explicit ABI padding")
        c += f'SHIP_ASSERT(offsetof({ctype}, {field}) == {offset}, "{name}.{field}");\n'
        a += f"export const {snake(name).upper()}_{field.upper()}: u32 = {offset};\n"
        offset += size(ty)
    sizes[name] = offset
    alignments[name] = record_alignment
    if offset % record_alignment:
        raise ValueError(f"{name} needs explicit trailing ABI padding")
    c += f'SHIP_ASSERT(sizeof({ctype}) == {offset}, "{name} size");\n'
    c += f'SHIP_ASSERT(SHIP_ALIGNOF({ctype}) == {record_alignment}, "{name} alignment");\n'
    a += f"export const {snake(name).upper()}_SIZE: u32 = {offset};\n"
raw = source[source.index('pub mod raw'):]
for name, params, ret in re.findall(r"pub fn (\w+)\((.*?)\)\s*->\s*(\w+)\s*;", raw, re.S):
    cp, ap = [], []
    for param in params.split(','):
        if not param.strip():
            continue
        arg, ty = [s.strip() for s in param.split(':', 1)]
        if ty.startswith("*"):
            target = normalize(ty.split(" ", 1)[1])
            base = "void" if target == "u8" else cfield("", target).rstrip("; ")
            cty = ("const " if ty.startswith("*const") else "") + base + " *"
        else:
            cty = primitives[ty][1]
        cp.append(f"{cty} {arg}")
        ap.append(f"{arg}: " + ("usize" if ty.startswith('*') else ty))
    cr = {"i32":"int32_t", "u64":"uint64_t"}[ret]
    c += f'SHIP_IMPORT("{name}") {cr} ship_{name}({", ".join(cp) or "void"});\n'
    a += f'@external("{import_module}", "{name}")\nexport declare function {name}({", ".join(ap)}): {ret};\n'
c += '''/* Guest exports: uint32_t ship_api_version(void); void ship_tick(void); memory. */
#ifdef __cplusplus
}
#endif
#endif
'''
c = c.replace("__IMPORT_MODULE__", import_module)
(API / 'include/ship.h').write_text(c)
(API / 'bindings/ship.ts').write_text(a)
