[package]
name = "toy-sim-client"
version.workspace = true
edition.workspace = true

[features]
default = []
profile = ["ui", "bevy/trace_chrome"]
ui = ["dep:bevy", "dep:toy-sim-ui", "dep:toy-sim-ship-view", "dep:toy-sim-stars", "dep:toy-sim-space", "dep:toy-sim-universe", "dep:hifitime"]

[dependencies]
bevy = { workspace = true, optional = true }
toy-sim-ui = { path = "../toy-sim-ui", optional = true }
toy-sim-ship-view = { path = "../toy-sim-ship-view", optional = true }
toy-sim-net = { path = "../toy-sim-net" }
tokio = { version = "1.53", features = ["rt-multi-thread", "sync", "time"] }
ed25519-dalek = "2.2"

anyhow.workspace = true
blake3 = "1.8"
toy-sim-ships = { path = "../toy-sim-ships" }
toml.workspace = true
serde.workspace = true
toy-sim-model = { path = "../toy-sim-model" }
toy-sim-protocol = { path = "../toy-sim-protocol" }
glam.workspace = true

toy-sim-stars = { path = "../toy-sim-stars", optional = true }

toy-sim-space = { path = "../toy-sim-space", optional = true }

toy-sim-universe = { path = "../toy-sim-universe", optional = true }
hifitime = { version = "4.3.1", optional = true }

[[bin]]
name = "toy-sim-client"
path = "src/main.rs"
required-features = ["ui"]
